/*
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.loginradius.sdk.internal.openapi.api;

import com.loginradius.sdk.internal.openapi.ApiCallback;
import com.loginradius.sdk.internal.openapi.ApiClient;
import com.loginradius.sdk.internal.openapi.ApiException;
import com.loginradius.sdk.internal.openapi.ApiResponse;
import com.loginradius.sdk.internal.openapi.Configuration;
import com.loginradius.sdk.internal.openapi.Pair;
import com.loginradius.sdk.internal.openapi.ProgressRequestBody;
import com.loginradius.sdk.internal.openapi.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.loginradius.sdk.internal.openapi.model.JWKSResponse;
import com.loginradius.sdk.internal.openapi.model.OAuthErrorResponse;
import com.loginradius.sdk.internal.openapi.model.OAuthM2MIntrospectResponse;
import com.loginradius.sdk.internal.openapi.model.OAuthM2MTokenGenerate;
import com.loginradius.sdk.internal.openapi.model.OAuthM2MTokenIntrospect;
import com.loginradius.sdk.internal.openapi.model.OAuthM2MTokenResponse;
import com.loginradius.sdk.internal.openapi.model.OAuthM2MTokenRevoke;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class OAuthM2MApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public OAuthM2MApi() {
        this(Configuration.getDefaultApiClient());
    }

    public OAuthM2MApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for generateM2MToken
     * @param oauthM2MTokenGenerate  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Status Unauthorized: The client must authenticate itself to get the requested response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateM2MTokenCall(OAuthM2MTokenGenerate oauthM2MTokenGenerate, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] { "https://{TenantName}.hub.loginradius.com", "https://{CustomDomain}" };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = oauthM2MTokenGenerate;

        // create path and map variables
        String localVarPath = "/service/oauth/token";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json",
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey", "ClientId" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call generateM2MTokenValidateBeforeCall(OAuthM2MTokenGenerate oauthM2MTokenGenerate, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'oauthM2MTokenGenerate' is set
        if (oauthM2MTokenGenerate == null) {
            throw new ApiException("Missing the required parameter 'oauthM2MTokenGenerate' when calling generateM2MToken(Async)");
        }

        return generateM2MTokenCall(oauthM2MTokenGenerate, _callback);

    }

    /**
     * Generate M2M token
     * Generates a Machine-to-Machine (M2M) token for application authentication.
     * @param oauthM2MTokenGenerate  (required)
     * @return OAuthM2MTokenResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Status Unauthorized: The client must authenticate itself to get the requested response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
     </table>
     */
    public OAuthM2MTokenResponse generateM2MToken(OAuthM2MTokenGenerate oauthM2MTokenGenerate) throws ApiException {
        ApiResponse<OAuthM2MTokenResponse> localVarResp = generateM2MTokenWithHttpInfo(oauthM2MTokenGenerate);
        return localVarResp.getData();
    }

    /**
     * Generate M2M token
     * Generates a Machine-to-Machine (M2M) token for application authentication.
     * @param oauthM2MTokenGenerate  (required)
     * @return ApiResponse&lt;OAuthM2MTokenResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Status Unauthorized: The client must authenticate itself to get the requested response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<OAuthM2MTokenResponse> generateM2MTokenWithHttpInfo(OAuthM2MTokenGenerate oauthM2MTokenGenerate) throws ApiException {
        okhttp3.Call localVarCall = generateM2MTokenValidateBeforeCall(oauthM2MTokenGenerate, null);
        Type localVarReturnType = new TypeToken<OAuthM2MTokenResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Generate M2M token (asynchronously)
     * Generates a Machine-to-Machine (M2M) token for application authentication.
     * @param oauthM2MTokenGenerate  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Status Unauthorized: The client must authenticate itself to get the requested response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateM2MTokenAsync(OAuthM2MTokenGenerate oauthM2MTokenGenerate, final ApiCallback<OAuthM2MTokenResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = generateM2MTokenValidateBeforeCall(oauthM2MTokenGenerate, _callback);
        Type localVarReturnType = new TypeToken<OAuthM2MTokenResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getM2MJWKSConfig
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getM2MJWKSConfigCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] { "https://{TenantName}.hub.loginradius.com", "https://{CustomDomain}" };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/service/oauth/jwks";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey", "ClientId" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getM2MJWKSConfigValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getM2MJWKSConfigCall(_callback);

    }

    /**
     * Retrieve JSON Web Key Set
     * Retrieves the JSON Web Key Set (JWKS) for verifying token signatures.
     * @return JWKSResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
     </table>
     */
    public JWKSResponse getM2MJWKSConfig() throws ApiException {
        ApiResponse<JWKSResponse> localVarResp = getM2MJWKSConfigWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Retrieve JSON Web Key Set
     * Retrieves the JSON Web Key Set (JWKS) for verifying token signatures.
     * @return ApiResponse&lt;JWKSResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<JWKSResponse> getM2MJWKSConfigWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getM2MJWKSConfigValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<JWKSResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve JSON Web Key Set (asynchronously)
     * Retrieves the JSON Web Key Set (JWKS) for verifying token signatures.
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getM2MJWKSConfigAsync(final ApiCallback<JWKSResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getM2MJWKSConfigValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<JWKSResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getM2MTokenInfo
     * @param oauthM2MTokenIntrospect  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Status Unauthorized: The client must authenticate itself to get the requested response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getM2MTokenInfoCall(OAuthM2MTokenIntrospect oauthM2MTokenIntrospect, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] { "https://{TenantName}.hub.loginradius.com", "https://{CustomDomain}" };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = oauthM2MTokenIntrospect;

        // create path and map variables
        String localVarPath = "/service/oauth/introspect";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json",
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey", "ClientId" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getM2MTokenInfoValidateBeforeCall(OAuthM2MTokenIntrospect oauthM2MTokenIntrospect, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'oauthM2MTokenIntrospect' is set
        if (oauthM2MTokenIntrospect == null) {
            throw new ApiException("Missing the required parameter 'oauthM2MTokenIntrospect' when calling getM2MTokenInfo(Async)");
        }

        return getM2MTokenInfoCall(oauthM2MTokenIntrospect, _callback);

    }

    /**
     * Retrieve M2M token info
     * Retrieves information about a Machine-to-Machine (M2M) token.
     * @param oauthM2MTokenIntrospect  (required)
     * @return OAuthM2MIntrospectResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Status Unauthorized: The client must authenticate itself to get the requested response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
     </table>
     */
    public OAuthM2MIntrospectResponse getM2MTokenInfo(OAuthM2MTokenIntrospect oauthM2MTokenIntrospect) throws ApiException {
        ApiResponse<OAuthM2MIntrospectResponse> localVarResp = getM2MTokenInfoWithHttpInfo(oauthM2MTokenIntrospect);
        return localVarResp.getData();
    }

    /**
     * Retrieve M2M token info
     * Retrieves information about a Machine-to-Machine (M2M) token.
     * @param oauthM2MTokenIntrospect  (required)
     * @return ApiResponse&lt;OAuthM2MIntrospectResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Status Unauthorized: The client must authenticate itself to get the requested response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<OAuthM2MIntrospectResponse> getM2MTokenInfoWithHttpInfo(OAuthM2MTokenIntrospect oauthM2MTokenIntrospect) throws ApiException {
        okhttp3.Call localVarCall = getM2MTokenInfoValidateBeforeCall(oauthM2MTokenIntrospect, null);
        Type localVarReturnType = new TypeToken<OAuthM2MIntrospectResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve M2M token info (asynchronously)
     * Retrieves information about a Machine-to-Machine (M2M) token.
     * @param oauthM2MTokenIntrospect  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Status Unauthorized: The client must authenticate itself to get the requested response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getM2MTokenInfoAsync(OAuthM2MTokenIntrospect oauthM2MTokenIntrospect, final ApiCallback<OAuthM2MIntrospectResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getM2MTokenInfoValidateBeforeCall(oauthM2MTokenIntrospect, _callback);
        Type localVarReturnType = new TypeToken<OAuthM2MIntrospectResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for revokeM2MToken
     * @param oauthM2MTokenRevoke  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Status Unauthorized: The client must authenticate itself to get the requested response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call revokeM2MTokenCall(OAuthM2MTokenRevoke oauthM2MTokenRevoke, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] { "https://{TenantName}.hub.loginradius.com", "https://{CustomDomain}" };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = oauthM2MTokenRevoke;

        // create path and map variables
        String localVarPath = "/service/oauth/revoke";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json",
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey", "ClientId" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call revokeM2MTokenValidateBeforeCall(OAuthM2MTokenRevoke oauthM2MTokenRevoke, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'oauthM2MTokenRevoke' is set
        if (oauthM2MTokenRevoke == null) {
            throw new ApiException("Missing the required parameter 'oauthM2MTokenRevoke' when calling revokeM2MToken(Async)");
        }

        return revokeM2MTokenCall(oauthM2MTokenRevoke, _callback);

    }

    /**
     * Revoke M2M token
     * Revokes a Machine-to-Machine (M2M) token to invalidate it.
     * @param oauthM2MTokenRevoke  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Status Unauthorized: The client must authenticate itself to get the requested response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
     </table>
     */
    public void revokeM2MToken(OAuthM2MTokenRevoke oauthM2MTokenRevoke) throws ApiException {
        revokeM2MTokenWithHttpInfo(oauthM2MTokenRevoke);
    }

    /**
     * Revoke M2M token
     * Revokes a Machine-to-Machine (M2M) token to invalidate it.
     * @param oauthM2MTokenRevoke  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Status Unauthorized: The client must authenticate itself to get the requested response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> revokeM2MTokenWithHttpInfo(OAuthM2MTokenRevoke oauthM2MTokenRevoke) throws ApiException {
        okhttp3.Call localVarCall = revokeM2MTokenValidateBeforeCall(oauthM2MTokenRevoke, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Revoke M2M token (asynchronously)
     * Revokes a Machine-to-Machine (M2M) token to invalidate it.
     * @param oauthM2MTokenRevoke  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Status Unauthorized: The client must authenticate itself to get the requested response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call revokeM2MTokenAsync(OAuthM2MTokenRevoke oauthM2MTokenRevoke, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = revokeM2MTokenValidateBeforeCall(oauthM2MTokenRevoke, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
