/*
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.loginradius.sdk.internal.openapi.api;

import com.loginradius.sdk.internal.openapi.ApiCallback;
import com.loginradius.sdk.internal.openapi.ApiClient;
import com.loginradius.sdk.internal.openapi.ApiException;
import com.loginradius.sdk.internal.openapi.ApiResponse;
import com.loginradius.sdk.internal.openapi.Configuration;
import com.loginradius.sdk.internal.openapi.Pair;
import com.loginradius.sdk.internal.openapi.ProgressRequestBody;
import com.loginradius.sdk.internal.openapi.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.loginradius.sdk.internal.openapi.model.AddOrganizationDomainRequest;
import com.loginradius.sdk.internal.openapi.model.DeleteResponse;
import com.loginradius.sdk.internal.openapi.model.ErrorResponse;
import com.loginradius.sdk.internal.openapi.model.GetAllOrganizationDomains200Response;
import com.loginradius.sdk.internal.openapi.model.OrganizationsDomainsResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class OrganizationDomainsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public OrganizationDomainsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public OrganizationDomainsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for addOrganizationDomain
     * @param orgId Organization ID (required)
     * @param addOrganizationDomainRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addOrganizationDomainCall(String orgId, AddOrganizationDomainRequest addOrganizationDomainRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = addOrganizationDomainRequest;

        // create path and map variables
        String localVarPath = "/v2/manage/organizations/{orgId}/domains"
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey", "M2MBearerToken", "ClientSecret", "ClientId", "APISecret" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call addOrganizationDomainValidateBeforeCall(String orgId, AddOrganizationDomainRequest addOrganizationDomainRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling addOrganizationDomain(Async)");
        }

        // verify the required parameter 'addOrganizationDomainRequest' is set
        if (addOrganizationDomainRequest == null) {
            throw new ApiException("Missing the required parameter 'addOrganizationDomainRequest' when calling addOrganizationDomain(Async)");
        }

        return addOrganizationDomainCall(orgId, addOrganizationDomainRequest, _callback);

    }

    /**
     * Add Organization domain
     * Adds a new domain to an Organization.
     * @param orgId Organization ID (required)
     * @param addOrganizationDomainRequest  (required)
     * @return OrganizationsDomainsResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public OrganizationsDomainsResponse addOrganizationDomain(String orgId, AddOrganizationDomainRequest addOrganizationDomainRequest) throws ApiException {
        ApiResponse<OrganizationsDomainsResponse> localVarResp = addOrganizationDomainWithHttpInfo(orgId, addOrganizationDomainRequest);
        return localVarResp.getData();
    }

    /**
     * Add Organization domain
     * Adds a new domain to an Organization.
     * @param orgId Organization ID (required)
     * @param addOrganizationDomainRequest  (required)
     * @return ApiResponse&lt;OrganizationsDomainsResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<OrganizationsDomainsResponse> addOrganizationDomainWithHttpInfo(String orgId, AddOrganizationDomainRequest addOrganizationDomainRequest) throws ApiException {
        okhttp3.Call localVarCall = addOrganizationDomainValidateBeforeCall(orgId, addOrganizationDomainRequest, null);
        Type localVarReturnType = new TypeToken<OrganizationsDomainsResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Add Organization domain (asynchronously)
     * Adds a new domain to an Organization.
     * @param orgId Organization ID (required)
     * @param addOrganizationDomainRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addOrganizationDomainAsync(String orgId, AddOrganizationDomainRequest addOrganizationDomainRequest, final ApiCallback<OrganizationsDomainsResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = addOrganizationDomainValidateBeforeCall(orgId, addOrganizationDomainRequest, _callback);
        Type localVarReturnType = new TypeToken<OrganizationsDomainsResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteOrganizationDomain
     * @param orgId Organization ID (required)
     * @param domainId Organization Domain ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteOrganizationDomainCall(String orgId, String domainId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/manage/organizations/{orgId}/domains/{domainId}"
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()))
            .replace("{" + "domainId" + "}", localVarApiClient.escapeString(domainId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey", "M2MBearerToken", "ClientSecret", "ClientId", "APISecret" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteOrganizationDomainValidateBeforeCall(String orgId, String domainId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling deleteOrganizationDomain(Async)");
        }

        // verify the required parameter 'domainId' is set
        if (domainId == null) {
            throw new ApiException("Missing the required parameter 'domainId' when calling deleteOrganizationDomain(Async)");
        }

        return deleteOrganizationDomainCall(orgId, domainId, _callback);

    }

    /**
     * Delete Organization domain
     * Deletes a domain from an Organization.
     * @param orgId Organization ID (required)
     * @param domainId Organization Domain ID (required)
     * @return DeleteResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public DeleteResponse deleteOrganizationDomain(String orgId, String domainId) throws ApiException {
        ApiResponse<DeleteResponse> localVarResp = deleteOrganizationDomainWithHttpInfo(orgId, domainId);
        return localVarResp.getData();
    }

    /**
     * Delete Organization domain
     * Deletes a domain from an Organization.
     * @param orgId Organization ID (required)
     * @param domainId Organization Domain ID (required)
     * @return ApiResponse&lt;DeleteResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DeleteResponse> deleteOrganizationDomainWithHttpInfo(String orgId, String domainId) throws ApiException {
        okhttp3.Call localVarCall = deleteOrganizationDomainValidateBeforeCall(orgId, domainId, null);
        Type localVarReturnType = new TypeToken<DeleteResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Delete Organization domain (asynchronously)
     * Deletes a domain from an Organization.
     * @param orgId Organization ID (required)
     * @param domainId Organization Domain ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteOrganizationDomainAsync(String orgId, String domainId, final ApiCallback<DeleteResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteOrganizationDomainValidateBeforeCall(orgId, domainId, _callback);
        Type localVarReturnType = new TypeToken<DeleteResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getAllOrganizationDomains
     * @param orgId Organization ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllOrganizationDomainsCall(String orgId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/manage/organizations/{orgId}/domains"
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey", "M2MBearerToken", "ClientSecret", "ClientId", "APISecret" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAllOrganizationDomainsValidateBeforeCall(String orgId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling getAllOrganizationDomains(Async)");
        }

        return getAllOrganizationDomainsCall(orgId, _callback);

    }

    /**
     * List Organization domains
     * Lists all domains associated with an Organization.
     * @param orgId Organization ID (required)
     * @return GetAllOrganizationDomains200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public GetAllOrganizationDomains200Response getAllOrganizationDomains(String orgId) throws ApiException {
        ApiResponse<GetAllOrganizationDomains200Response> localVarResp = getAllOrganizationDomainsWithHttpInfo(orgId);
        return localVarResp.getData();
    }

    /**
     * List Organization domains
     * Lists all domains associated with an Organization.
     * @param orgId Organization ID (required)
     * @return ApiResponse&lt;GetAllOrganizationDomains200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetAllOrganizationDomains200Response> getAllOrganizationDomainsWithHttpInfo(String orgId) throws ApiException {
        okhttp3.Call localVarCall = getAllOrganizationDomainsValidateBeforeCall(orgId, null);
        Type localVarReturnType = new TypeToken<GetAllOrganizationDomains200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List Organization domains (asynchronously)
     * Lists all domains associated with an Organization.
     * @param orgId Organization ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllOrganizationDomainsAsync(String orgId, final ApiCallback<GetAllOrganizationDomains200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAllOrganizationDomainsValidateBeforeCall(orgId, _callback);
        Type localVarReturnType = new TypeToken<GetAllOrganizationDomains200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getOrganizationDomain
     * @param orgId Organization ID (required)
     * @param domainId Organization Domain ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getOrganizationDomainCall(String orgId, String domainId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/manage/organizations/{orgId}/domains/{domainId}"
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()))
            .replace("{" + "domainId" + "}", localVarApiClient.escapeString(domainId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey", "M2MBearerToken", "ClientSecret", "ClientId", "APISecret" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getOrganizationDomainValidateBeforeCall(String orgId, String domainId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling getOrganizationDomain(Async)");
        }

        // verify the required parameter 'domainId' is set
        if (domainId == null) {
            throw new ApiException("Missing the required parameter 'domainId' when calling getOrganizationDomain(Async)");
        }

        return getOrganizationDomainCall(orgId, domainId, _callback);

    }

    /**
     * Retrieve Organization domain
     * Retrieves details of a specific Organization domain.
     * @param orgId Organization ID (required)
     * @param domainId Organization Domain ID (required)
     * @return OrganizationsDomainsResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public OrganizationsDomainsResponse getOrganizationDomain(String orgId, String domainId) throws ApiException {
        ApiResponse<OrganizationsDomainsResponse> localVarResp = getOrganizationDomainWithHttpInfo(orgId, domainId);
        return localVarResp.getData();
    }

    /**
     * Retrieve Organization domain
     * Retrieves details of a specific Organization domain.
     * @param orgId Organization ID (required)
     * @param domainId Organization Domain ID (required)
     * @return ApiResponse&lt;OrganizationsDomainsResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<OrganizationsDomainsResponse> getOrganizationDomainWithHttpInfo(String orgId, String domainId) throws ApiException {
        okhttp3.Call localVarCall = getOrganizationDomainValidateBeforeCall(orgId, domainId, null);
        Type localVarReturnType = new TypeToken<OrganizationsDomainsResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve Organization domain (asynchronously)
     * Retrieves details of a specific Organization domain.
     * @param orgId Organization ID (required)
     * @param domainId Organization Domain ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getOrganizationDomainAsync(String orgId, String domainId, final ApiCallback<OrganizationsDomainsResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getOrganizationDomainValidateBeforeCall(orgId, domainId, _callback);
        Type localVarReturnType = new TypeToken<OrganizationsDomainsResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for verifyOrganizationDomain
     * @param domainId Organization Domain ID (required)
     * @param orgId Organization ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call verifyOrganizationDomainCall(String domainId, String orgId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/manage/organizations/{orgId}/domains/{domainId}"
            .replace("{" + "domainId" + "}", localVarApiClient.escapeString(domainId.toString()))
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey", "M2MBearerToken", "ClientSecret", "ClientId", "APISecret" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call verifyOrganizationDomainValidateBeforeCall(String domainId, String orgId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'domainId' is set
        if (domainId == null) {
            throw new ApiException("Missing the required parameter 'domainId' when calling verifyOrganizationDomain(Async)");
        }

        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling verifyOrganizationDomain(Async)");
        }

        return verifyOrganizationDomainCall(domainId, orgId, _callback);

    }

    /**
     * Verify Organization domain
     * Verifies the ownership of an Organization domain.
     * @param domainId Organization Domain ID (required)
     * @param orgId Organization ID (required)
     * @return OrganizationsDomainsResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public OrganizationsDomainsResponse verifyOrganizationDomain(String domainId, String orgId) throws ApiException {
        ApiResponse<OrganizationsDomainsResponse> localVarResp = verifyOrganizationDomainWithHttpInfo(domainId, orgId);
        return localVarResp.getData();
    }

    /**
     * Verify Organization domain
     * Verifies the ownership of an Organization domain.
     * @param domainId Organization Domain ID (required)
     * @param orgId Organization ID (required)
     * @return ApiResponse&lt;OrganizationsDomainsResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<OrganizationsDomainsResponse> verifyOrganizationDomainWithHttpInfo(String domainId, String orgId) throws ApiException {
        okhttp3.Call localVarCall = verifyOrganizationDomainValidateBeforeCall(domainId, orgId, null);
        Type localVarReturnType = new TypeToken<OrganizationsDomainsResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Verify Organization domain (asynchronously)
     * Verifies the ownership of an Organization domain.
     * @param domainId Organization Domain ID (required)
     * @param orgId Organization ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call verifyOrganizationDomainAsync(String domainId, String orgId, final ApiCallback<OrganizationsDomainsResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = verifyOrganizationDomainValidateBeforeCall(domainId, orgId, _callback);
        Type localVarReturnType = new TypeToken<OrganizationsDomainsResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
