/*
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.loginradius.sdk.internal.openapi.api;

import com.loginradius.sdk.internal.openapi.ApiCallback;
import com.loginradius.sdk.internal.openapi.ApiClient;
import com.loginradius.sdk.internal.openapi.ApiException;
import com.loginradius.sdk.internal.openapi.ApiResponse;
import com.loginradius.sdk.internal.openapi.Configuration;
import com.loginradius.sdk.internal.openapi.Pair;
import com.loginradius.sdk.internal.openapi.ProgressRequestBody;
import com.loginradius.sdk.internal.openapi.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.loginradius.sdk.internal.openapi.model.ErrorResponse;
import com.loginradius.sdk.internal.openapi.model.GetInvitationsByOrgId200Response;
import com.loginradius.sdk.internal.openapi.model.Invitation;
import com.loginradius.sdk.internal.openapi.model.ResendInvitation;
import com.loginradius.sdk.internal.openapi.model.SendInvitation;
import com.loginradius.sdk.internal.openapi.model.UpdateInvitationByInvitationIdRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class OrganizationInvitationsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public OrganizationInvitationsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public OrganizationInvitationsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for deleteInvitationByInvitationId
     * @param invitationid The ID of the invitation. The ID is typically in the format *inv_&lt;unique_id&gt;*, where *&lt;unique_id&gt;* is a string of alphanumeric characters. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteInvitationByInvitationIdCall(String invitationid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/manage/invitations/{invitationid}"
            .replace("{" + "invitationid" + "}", localVarApiClient.escapeString(invitationid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey", "M2MBearerToken", "ClientSecret", "ClientId", "APISecret" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteInvitationByInvitationIdValidateBeforeCall(String invitationid, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'invitationid' is set
        if (invitationid == null) {
            throw new ApiException("Missing the required parameter 'invitationid' when calling deleteInvitationByInvitationId(Async)");
        }

        return deleteInvitationByInvitationIdCall(invitationid, _callback);

    }

    /**
     * Delete invitation by ID
     * Deletes or revokes an invitation by invitation ID.
     * @param invitationid The ID of the invitation. The ID is typically in the format *inv_&lt;unique_id&gt;*, where *&lt;unique_id&gt;* is a string of alphanumeric characters. (required)
     * @return Invitation
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public Invitation deleteInvitationByInvitationId(String invitationid) throws ApiException {
        ApiResponse<Invitation> localVarResp = deleteInvitationByInvitationIdWithHttpInfo(invitationid);
        return localVarResp.getData();
    }

    /**
     * Delete invitation by ID
     * Deletes or revokes an invitation by invitation ID.
     * @param invitationid The ID of the invitation. The ID is typically in the format *inv_&lt;unique_id&gt;*, where *&lt;unique_id&gt;* is a string of alphanumeric characters. (required)
     * @return ApiResponse&lt;Invitation&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Invitation> deleteInvitationByInvitationIdWithHttpInfo(String invitationid) throws ApiException {
        okhttp3.Call localVarCall = deleteInvitationByInvitationIdValidateBeforeCall(invitationid, null);
        Type localVarReturnType = new TypeToken<Invitation>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Delete invitation by ID (asynchronously)
     * Deletes or revokes an invitation by invitation ID.
     * @param invitationid The ID of the invitation. The ID is typically in the format *inv_&lt;unique_id&gt;*, where *&lt;unique_id&gt;* is a string of alphanumeric characters. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteInvitationByInvitationIdAsync(String invitationid, final ApiCallback<Invitation> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteInvitationByInvitationIdValidateBeforeCall(invitationid, _callback);
        Type localVarReturnType = new TypeToken<Invitation>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getInvitationsByOrgId
     * @param orgid  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getInvitationsByOrgIdCall(String orgid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/manage/invitations";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (orgid != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("orgid", orgid));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey", "M2MBearerToken", "ClientSecret", "ClientId", "APISecret" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getInvitationsByOrgIdValidateBeforeCall(String orgid, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orgid' is set
        if (orgid == null) {
            throw new ApiException("Missing the required parameter 'orgid' when calling getInvitationsByOrgId(Async)");
        }

        return getInvitationsByOrgIdCall(orgid, _callback);

    }

    /**
     * List invitations by Organization ID
     * Lists all invitations by Organization ID.
     * @param orgid  (required)
     * @return GetInvitationsByOrgId200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public GetInvitationsByOrgId200Response getInvitationsByOrgId(String orgid) throws ApiException {
        ApiResponse<GetInvitationsByOrgId200Response> localVarResp = getInvitationsByOrgIdWithHttpInfo(orgid);
        return localVarResp.getData();
    }

    /**
     * List invitations by Organization ID
     * Lists all invitations by Organization ID.
     * @param orgid  (required)
     * @return ApiResponse&lt;GetInvitationsByOrgId200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetInvitationsByOrgId200Response> getInvitationsByOrgIdWithHttpInfo(String orgid) throws ApiException {
        okhttp3.Call localVarCall = getInvitationsByOrgIdValidateBeforeCall(orgid, null);
        Type localVarReturnType = new TypeToken<GetInvitationsByOrgId200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List invitations by Organization ID (asynchronously)
     * Lists all invitations by Organization ID.
     * @param orgid  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getInvitationsByOrgIdAsync(String orgid, final ApiCallback<GetInvitationsByOrgId200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getInvitationsByOrgIdValidateBeforeCall(orgid, _callback);
        Type localVarReturnType = new TypeToken<GetInvitationsByOrgId200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for resendInvitationByInvitationId
     * @param invitationid The ID of the invitation. The ID is typically in the format *inv_&lt;unique_id&gt;*, where *&lt;unique_id&gt;* is a string of alphanumeric characters. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call resendInvitationByInvitationIdCall(String invitationid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/manage/invitations/{invitationid}/resend"
            .replace("{" + "invitationid" + "}", localVarApiClient.escapeString(invitationid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey", "M2MBearerToken", "ClientSecret", "ClientId", "APISecret" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call resendInvitationByInvitationIdValidateBeforeCall(String invitationid, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'invitationid' is set
        if (invitationid == null) {
            throw new ApiException("Missing the required parameter 'invitationid' when calling resendInvitationByInvitationId(Async)");
        }

        return resendInvitationByInvitationIdCall(invitationid, _callback);

    }

    /**
     * Resend invitation by ID
     * Resends an invitation by invitation ID.
     * @param invitationid The ID of the invitation. The ID is typically in the format *inv_&lt;unique_id&gt;*, where *&lt;unique_id&gt;* is a string of alphanumeric characters. (required)
     * @return ResendInvitation
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ResendInvitation resendInvitationByInvitationId(String invitationid) throws ApiException {
        ApiResponse<ResendInvitation> localVarResp = resendInvitationByInvitationIdWithHttpInfo(invitationid);
        return localVarResp.getData();
    }

    /**
     * Resend invitation by ID
     * Resends an invitation by invitation ID.
     * @param invitationid The ID of the invitation. The ID is typically in the format *inv_&lt;unique_id&gt;*, where *&lt;unique_id&gt;* is a string of alphanumeric characters. (required)
     * @return ApiResponse&lt;ResendInvitation&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ResendInvitation> resendInvitationByInvitationIdWithHttpInfo(String invitationid) throws ApiException {
        okhttp3.Call localVarCall = resendInvitationByInvitationIdValidateBeforeCall(invitationid, null);
        Type localVarReturnType = new TypeToken<ResendInvitation>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Resend invitation by ID (asynchronously)
     * Resends an invitation by invitation ID.
     * @param invitationid The ID of the invitation. The ID is typically in the format *inv_&lt;unique_id&gt;*, where *&lt;unique_id&gt;* is a string of alphanumeric characters. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call resendInvitationByInvitationIdAsync(String invitationid, final ApiCallback<ResendInvitation> _callback) throws ApiException {

        okhttp3.Call localVarCall = resendInvitationByInvitationIdValidateBeforeCall(invitationid, _callback);
        Type localVarReturnType = new TypeToken<ResendInvitation>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for sendInvitation
     * @param sendInvitation  (required)
     * @param invitationUrl The URL to which the User will be redirected after accepting the invitation. This URL should be a valid URL and can include query parameters if needed. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Invitation sent successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call sendInvitationCall(SendInvitation sendInvitation, String invitationUrl, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = sendInvitation;

        // create path and map variables
        String localVarPath = "/v2/manage/invitations";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (invitationUrl != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("invitation_url", invitationUrl));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey", "M2MBearerToken", "ClientSecret", "ClientId", "APISecret" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call sendInvitationValidateBeforeCall(SendInvitation sendInvitation, String invitationUrl, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'sendInvitation' is set
        if (sendInvitation == null) {
            throw new ApiException("Missing the required parameter 'sendInvitation' when calling sendInvitation(Async)");
        }

        return sendInvitationCall(sendInvitation, invitationUrl, _callback);

    }

    /**
     * Send invitation
     * Sends a new invitation.
     * @param sendInvitation  (required)
     * @param invitationUrl The URL to which the User will be redirected after accepting the invitation. This URL should be a valid URL and can include query parameters if needed. (optional)
     * @return Invitation
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Invitation sent successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public Invitation sendInvitation(SendInvitation sendInvitation, String invitationUrl) throws ApiException {
        ApiResponse<Invitation> localVarResp = sendInvitationWithHttpInfo(sendInvitation, invitationUrl);
        return localVarResp.getData();
    }

    /**
     * Send invitation
     * Sends a new invitation.
     * @param sendInvitation  (required)
     * @param invitationUrl The URL to which the User will be redirected after accepting the invitation. This URL should be a valid URL and can include query parameters if needed. (optional)
     * @return ApiResponse&lt;Invitation&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Invitation sent successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Invitation> sendInvitationWithHttpInfo(SendInvitation sendInvitation, String invitationUrl) throws ApiException {
        okhttp3.Call localVarCall = sendInvitationValidateBeforeCall(sendInvitation, invitationUrl, null);
        Type localVarReturnType = new TypeToken<Invitation>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Send invitation (asynchronously)
     * Sends a new invitation.
     * @param sendInvitation  (required)
     * @param invitationUrl The URL to which the User will be redirected after accepting the invitation. This URL should be a valid URL and can include query parameters if needed. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Invitation sent successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call sendInvitationAsync(SendInvitation sendInvitation, String invitationUrl, final ApiCallback<Invitation> _callback) throws ApiException {

        okhttp3.Call localVarCall = sendInvitationValidateBeforeCall(sendInvitation, invitationUrl, _callback);
        Type localVarReturnType = new TypeToken<Invitation>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateInvitationByInvitationId
     * @param invitationid The ID of the invitation. The ID is typically in the format *inv_&lt;unique_id&gt;*, where *&lt;unique_id&gt;* is a string of alphanumeric characters. (required)
     * @param updateInvitationByInvitationIdRequest  (required)
     * @param invitationUrl The URL to which the User will be redirected after accepting the invitation. This URL should be a valid URL and can include query parameters if needed. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateInvitationByInvitationIdCall(String invitationid, UpdateInvitationByInvitationIdRequest updateInvitationByInvitationIdRequest, String invitationUrl, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updateInvitationByInvitationIdRequest;

        // create path and map variables
        String localVarPath = "/v2/manage/invitations/{invitationid}"
            .replace("{" + "invitationid" + "}", localVarApiClient.escapeString(invitationid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (invitationUrl != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("invitation_url", invitationUrl));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey", "M2MBearerToken", "ClientSecret", "ClientId", "APISecret" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateInvitationByInvitationIdValidateBeforeCall(String invitationid, UpdateInvitationByInvitationIdRequest updateInvitationByInvitationIdRequest, String invitationUrl, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'invitationid' is set
        if (invitationid == null) {
            throw new ApiException("Missing the required parameter 'invitationid' when calling updateInvitationByInvitationId(Async)");
        }

        // verify the required parameter 'updateInvitationByInvitationIdRequest' is set
        if (updateInvitationByInvitationIdRequest == null) {
            throw new ApiException("Missing the required parameter 'updateInvitationByInvitationIdRequest' when calling updateInvitationByInvitationId(Async)");
        }

        return updateInvitationByInvitationIdCall(invitationid, updateInvitationByInvitationIdRequest, invitationUrl, _callback);

    }

    /**
     * Update invitation by ID
     * Updates invitation details by invitation ID.
     * @param invitationid The ID of the invitation. The ID is typically in the format *inv_&lt;unique_id&gt;*, where *&lt;unique_id&gt;* is a string of alphanumeric characters. (required)
     * @param updateInvitationByInvitationIdRequest  (required)
     * @param invitationUrl The URL to which the User will be redirected after accepting the invitation. This URL should be a valid URL and can include query parameters if needed. (optional)
     * @return Invitation
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public Invitation updateInvitationByInvitationId(String invitationid, UpdateInvitationByInvitationIdRequest updateInvitationByInvitationIdRequest, String invitationUrl) throws ApiException {
        ApiResponse<Invitation> localVarResp = updateInvitationByInvitationIdWithHttpInfo(invitationid, updateInvitationByInvitationIdRequest, invitationUrl);
        return localVarResp.getData();
    }

    /**
     * Update invitation by ID
     * Updates invitation details by invitation ID.
     * @param invitationid The ID of the invitation. The ID is typically in the format *inv_&lt;unique_id&gt;*, where *&lt;unique_id&gt;* is a string of alphanumeric characters. (required)
     * @param updateInvitationByInvitationIdRequest  (required)
     * @param invitationUrl The URL to which the User will be redirected after accepting the invitation. This URL should be a valid URL and can include query parameters if needed. (optional)
     * @return ApiResponse&lt;Invitation&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Invitation> updateInvitationByInvitationIdWithHttpInfo(String invitationid, UpdateInvitationByInvitationIdRequest updateInvitationByInvitationIdRequest, String invitationUrl) throws ApiException {
        okhttp3.Call localVarCall = updateInvitationByInvitationIdValidateBeforeCall(invitationid, updateInvitationByInvitationIdRequest, invitationUrl, null);
        Type localVarReturnType = new TypeToken<Invitation>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update invitation by ID (asynchronously)
     * Updates invitation details by invitation ID.
     * @param invitationid The ID of the invitation. The ID is typically in the format *inv_&lt;unique_id&gt;*, where *&lt;unique_id&gt;* is a string of alphanumeric characters. (required)
     * @param updateInvitationByInvitationIdRequest  (required)
     * @param invitationUrl The URL to which the User will be redirected after accepting the invitation. This URL should be a valid URL and can include query parameters if needed. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateInvitationByInvitationIdAsync(String invitationid, UpdateInvitationByInvitationIdRequest updateInvitationByInvitationIdRequest, String invitationUrl, final ApiCallback<Invitation> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateInvitationByInvitationIdValidateBeforeCall(invitationid, updateInvitationByInvitationIdRequest, invitationUrl, _callback);
        Type localVarReturnType = new TypeToken<Invitation>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
