/*
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.loginradius.sdk.internal.openapi.api;

import com.loginradius.sdk.internal.openapi.ApiCallback;
import com.loginradius.sdk.internal.openapi.ApiClient;
import com.loginradius.sdk.internal.openapi.ApiException;
import com.loginradius.sdk.internal.openapi.ApiResponse;
import com.loginradius.sdk.internal.openapi.Configuration;
import com.loginradius.sdk.internal.openapi.Pair;
import com.loginradius.sdk.internal.openapi.ProgressRequestBody;
import com.loginradius.sdk.internal.openapi.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.loginradius.sdk.internal.openapi.model.ErrorResponse;
import com.loginradius.sdk.internal.openapi.model.PushAuthenticator;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PushNotificationConfigurationApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public PushNotificationConfigurationApi() {
        this(Configuration.getDefaultApiClient());
    }

    public PushNotificationConfigurationApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createPushSettings
     * @param pushAuthenticator  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createPushSettingsCall(PushAuthenticator pushAuthenticator, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = pushAuthenticator;

        // create path and map variables
        String localVarPath = "/v2/manage/2fa/push-notification-settings";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "M2MBearerToken" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createPushSettingsValidateBeforeCall(PushAuthenticator pushAuthenticator, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'pushAuthenticator' is set
        if (pushAuthenticator == null) {
            throw new ApiException("Missing the required parameter 'pushAuthenticator' when calling createPushSettings(Async)");
        }

        return createPushSettingsCall(pushAuthenticator, _callback);

    }

    /**
     * Create Push Notification settings
     * Creates new Push Notification settings for second factor authentication.
     * @param pushAuthenticator  (required)
     * @return PushAuthenticator
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public PushAuthenticator createPushSettings(PushAuthenticator pushAuthenticator) throws ApiException {
        ApiResponse<PushAuthenticator> localVarResp = createPushSettingsWithHttpInfo(pushAuthenticator);
        return localVarResp.getData();
    }

    /**
     * Create Push Notification settings
     * Creates new Push Notification settings for second factor authentication.
     * @param pushAuthenticator  (required)
     * @return ApiResponse&lt;PushAuthenticator&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PushAuthenticator> createPushSettingsWithHttpInfo(PushAuthenticator pushAuthenticator) throws ApiException {
        okhttp3.Call localVarCall = createPushSettingsValidateBeforeCall(pushAuthenticator, null);
        Type localVarReturnType = new TypeToken<PushAuthenticator>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create Push Notification settings (asynchronously)
     * Creates new Push Notification settings for second factor authentication.
     * @param pushAuthenticator  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createPushSettingsAsync(PushAuthenticator pushAuthenticator, final ApiCallback<PushAuthenticator> _callback) throws ApiException {

        okhttp3.Call localVarCall = createPushSettingsValidateBeforeCall(pushAuthenticator, _callback);
        Type localVarReturnType = new TypeToken<PushAuthenticator>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getPushSettings
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPushSettingsCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/manage/2fa/push-notification-settings";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "M2MBearerToken" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPushSettingsValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getPushSettingsCall(_callback);

    }

    /**
     * Retrieve Push Notification settings
     * Retrieves the current Push Notification settings for second factor authentication.
     * @return PushAuthenticator
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public PushAuthenticator getPushSettings() throws ApiException {
        ApiResponse<PushAuthenticator> localVarResp = getPushSettingsWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Retrieve Push Notification settings
     * Retrieves the current Push Notification settings for second factor authentication.
     * @return ApiResponse&lt;PushAuthenticator&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PushAuthenticator> getPushSettingsWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getPushSettingsValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<PushAuthenticator>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve Push Notification settings (asynchronously)
     * Retrieves the current Push Notification settings for second factor authentication.
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPushSettingsAsync(final ApiCallback<PushAuthenticator> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPushSettingsValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<PushAuthenticator>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updatePushSettings
     * @param pushAuthenticator  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updatePushSettingsCall(PushAuthenticator pushAuthenticator, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = pushAuthenticator;

        // create path and map variables
        String localVarPath = "/v2/manage/2fa/push-notification-settings";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "M2MBearerToken" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updatePushSettingsValidateBeforeCall(PushAuthenticator pushAuthenticator, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'pushAuthenticator' is set
        if (pushAuthenticator == null) {
            throw new ApiException("Missing the required parameter 'pushAuthenticator' when calling updatePushSettings(Async)");
        }

        return updatePushSettingsCall(pushAuthenticator, _callback);

    }

    /**
     * Update Push Notification settings
     * Updates existing Push Notification settings for second factor authentication.
     * @param pushAuthenticator  (required)
     * @return PushAuthenticator
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public PushAuthenticator updatePushSettings(PushAuthenticator pushAuthenticator) throws ApiException {
        ApiResponse<PushAuthenticator> localVarResp = updatePushSettingsWithHttpInfo(pushAuthenticator);
        return localVarResp.getData();
    }

    /**
     * Update Push Notification settings
     * Updates existing Push Notification settings for second factor authentication.
     * @param pushAuthenticator  (required)
     * @return ApiResponse&lt;PushAuthenticator&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PushAuthenticator> updatePushSettingsWithHttpInfo(PushAuthenticator pushAuthenticator) throws ApiException {
        okhttp3.Call localVarCall = updatePushSettingsValidateBeforeCall(pushAuthenticator, null);
        Type localVarReturnType = new TypeToken<PushAuthenticator>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update Push Notification settings (asynchronously)
     * Updates existing Push Notification settings for second factor authentication.
     * @param pushAuthenticator  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found: The server cannot find the requested resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updatePushSettingsAsync(PushAuthenticator pushAuthenticator, final ApiCallback<PushAuthenticator> _callback) throws ApiException {

        okhttp3.Call localVarCall = updatePushSettingsValidateBeforeCall(pushAuthenticator, _callback);
        Type localVarReturnType = new TypeToken<PushAuthenticator>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
