/*
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.loginradius.sdk.internal.openapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.loginradius.sdk.internal.openapi.JSON;

/**
 * Body for the TOTP verification endpoints. LoginRadius has two authenticator generations and they do NOT share a field name: a tenant on Google Authenticator must send &#x60;googleauthenticatorcode&#x60;, while the newer generic authenticator uses &#x60;authenticatorcode&#x60;. Sending the wrong one returns ErrorCode 908 (\&quot;The googleauthenticatorcode is a required parameter.\&quot; / \&quot;The authenticatorcode is a required parameter.\&quot;), so both are declared here and callers populate whichever their tenant expects. DO NOT drop &#x60;googleauthenticatorcode&#x60; when refreshing this file from an external copy — tools/verify-spec-invariants.mjs will fail the build.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class AuthenticatorCodeRequest {
  public static final String SERIALIZED_NAME_GOOGLEAUTHENTICATORCODE = "googleauthenticatorcode";
  @SerializedName(SERIALIZED_NAME_GOOGLEAUTHENTICATORCODE)
  @javax.annotation.Nullable
  private String googleauthenticatorcode;

  public static final String SERIALIZED_NAME_AUTHENTICATORCODE = "authenticatorcode";
  @SerializedName(SERIALIZED_NAME_AUTHENTICATORCODE)
  @javax.annotation.Nullable
  private String authenticatorcode;

  public AuthenticatorCodeRequest() {
  }

  public AuthenticatorCodeRequest googleauthenticatorcode(@javax.annotation.Nullable String googleauthenticatorcode) {
    this.googleauthenticatorcode = googleauthenticatorcode;
    return this;
  }

  /**
   * The Google Authenticator (TOTP) code. Required by tenants configured for Google Authenticator.
   * @return googleauthenticatorcode
   */
  @javax.annotation.Nullable
  public String getGoogleauthenticatorcode() {
    return googleauthenticatorcode;
  }

  public void setGoogleauthenticatorcode(@javax.annotation.Nullable String googleauthenticatorcode) {
    this.googleauthenticatorcode = googleauthenticatorcode;
  }


  public AuthenticatorCodeRequest authenticatorcode(@javax.annotation.Nullable String authenticatorcode) {
    this.authenticatorcode = authenticatorcode;
    return this;
  }

  /**
   * The Authenticator code for multi-factor authentication. Used by tenants on the newer generic authenticator configuration.
   * @return authenticatorcode
   */
  @javax.annotation.Nullable
  public String getAuthenticatorcode() {
    return authenticatorcode;
  }

  public void setAuthenticatorcode(@javax.annotation.Nullable String authenticatorcode) {
    this.authenticatorcode = authenticatorcode;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the AuthenticatorCodeRequest instance itself
   */
  public AuthenticatorCodeRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthenticatorCodeRequest authenticatorCodeRequest = (AuthenticatorCodeRequest) o;
    return Objects.equals(this.googleauthenticatorcode, authenticatorCodeRequest.googleauthenticatorcode) &&
        Objects.equals(this.authenticatorcode, authenticatorCodeRequest.authenticatorcode)&&
        Objects.equals(this.additionalProperties, authenticatorCodeRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(googleauthenticatorcode, authenticatorcode, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthenticatorCodeRequest {\n");
    sb.append("    googleauthenticatorcode: ").append(toIndentedString(googleauthenticatorcode)).append("\n");
    sb.append("    authenticatorcode: ").append(toIndentedString(authenticatorcode)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("googleauthenticatorcode");
    openapiFields.add("authenticatorcode");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AuthenticatorCodeRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AuthenticatorCodeRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AuthenticatorCodeRequest is not found in the empty JSON string", AuthenticatorCodeRequest.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("googleauthenticatorcode") != null && !jsonObj.get("googleauthenticatorcode").isJsonNull()) && !jsonObj.get("googleauthenticatorcode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `googleauthenticatorcode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("googleauthenticatorcode").toString()));
      }
      if ((jsonObj.get("authenticatorcode") != null && !jsonObj.get("authenticatorcode").isJsonNull()) && !jsonObj.get("authenticatorcode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `authenticatorcode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("authenticatorcode").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AuthenticatorCodeRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AuthenticatorCodeRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AuthenticatorCodeRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AuthenticatorCodeRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<AuthenticatorCodeRequest>() {
           @Override
           public void write(JsonWriter out, AuthenticatorCodeRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public AuthenticatorCodeRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             AuthenticatorCodeRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AuthenticatorCodeRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AuthenticatorCodeRequest
   * @throws IOException if the JSON string is invalid with respect to AuthenticatorCodeRequest
   */
  public static AuthenticatorCodeRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AuthenticatorCodeRequest.class);
  }

  /**
   * Convert an instance of AuthenticatorCodeRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

