/*
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.loginradius.sdk.internal.openapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.loginradius.sdk.internal.openapi.JSON;

/**
 * LoginByUsernameRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class LoginByUsernameRequest {
  public static final String SERIALIZED_NAME_G_RECAPTCHA_RESPONSE = "g-recaptcha-response";
  @SerializedName(SERIALIZED_NAME_G_RECAPTCHA_RESPONSE)
  @javax.annotation.Nullable
  private String gRecaptchaResponse;

  public static final String SERIALIZED_NAME_QQ_CAPTCHA_TICKET = "qq_captcha_ticket";
  @SerializedName(SERIALIZED_NAME_QQ_CAPTCHA_TICKET)
  @javax.annotation.Nullable
  private String qqCaptchaTicket;

  public static final String SERIALIZED_NAME_QQ_CAPTCHA_RANDSTR = "qq_captcha_randstr";
  @SerializedName(SERIALIZED_NAME_QQ_CAPTCHA_RANDSTR)
  @javax.annotation.Nullable
  private String qqCaptchaRandstr;

  public static final String SERIALIZED_NAME_H_CAPTCHA_RESPONSE = "h-captcha-response";
  @SerializedName(SERIALIZED_NAME_H_CAPTCHA_RESPONSE)
  @javax.annotation.Nullable
  private String hCaptchaResponse;

  public static final String SERIALIZED_NAME_USERNAME = "username";
  @SerializedName(SERIALIZED_NAME_USERNAME)
  @javax.annotation.Nonnull
  private String username;

  public static final String SERIALIZED_NAME_PASSWORD = "password";
  @SerializedName(SERIALIZED_NAME_PASSWORD)
  @javax.annotation.Nonnull
  private String password;

  public static final String SERIALIZED_NAME_SECURITY_ANSWER = "securityAnswer";
  @SerializedName(SERIALIZED_NAME_SECURITY_ANSWER)
  @javax.annotation.Nullable
  private String securityAnswer;

  public LoginByUsernameRequest() {
  }

  public LoginByUsernameRequest gRecaptchaResponse(@javax.annotation.Nullable String gRecaptchaResponse) {
    this.gRecaptchaResponse = gRecaptchaResponse;
    return this;
  }

  /**
   * The Google reCAPTCHA response which is sent to the server for verification.
   * @return gRecaptchaResponse
   */
  @javax.annotation.Nullable
  public String getgRecaptchaResponse() {
    return gRecaptchaResponse;
  }

  public void setgRecaptchaResponse(@javax.annotation.Nullable String gRecaptchaResponse) {
    this.gRecaptchaResponse = gRecaptchaResponse;
  }


  public LoginByUsernameRequest qqCaptchaTicket(@javax.annotation.Nullable String qqCaptchaTicket) {
    this.qqCaptchaTicket = qqCaptchaTicket;
    return this;
  }

  /**
   * The QQ Captcha ticket which is sent to the server for verification.
   * @return qqCaptchaTicket
   */
  @javax.annotation.Nullable
  public String getQqCaptchaTicket() {
    return qqCaptchaTicket;
  }

  public void setQqCaptchaTicket(@javax.annotation.Nullable String qqCaptchaTicket) {
    this.qqCaptchaTicket = qqCaptchaTicket;
  }


  public LoginByUsernameRequest qqCaptchaRandstr(@javax.annotation.Nullable String qqCaptchaRandstr) {
    this.qqCaptchaRandstr = qqCaptchaRandstr;
    return this;
  }

  /**
   * The QQ Captcha random string which is sent to the server for verification.
   * @return qqCaptchaRandstr
   */
  @javax.annotation.Nullable
  public String getQqCaptchaRandstr() {
    return qqCaptchaRandstr;
  }

  public void setQqCaptchaRandstr(@javax.annotation.Nullable String qqCaptchaRandstr) {
    this.qqCaptchaRandstr = qqCaptchaRandstr;
  }


  public LoginByUsernameRequest hCaptchaResponse(@javax.annotation.Nullable String hCaptchaResponse) {
    this.hCaptchaResponse = hCaptchaResponse;
    return this;
  }

  /**
   * The hCaptcha response which is sent to the server for verification.
   * @return hCaptchaResponse
   */
  @javax.annotation.Nullable
  public String gethCaptchaResponse() {
    return hCaptchaResponse;
  }

  public void sethCaptchaResponse(@javax.annotation.Nullable String hCaptchaResponse) {
    this.hCaptchaResponse = hCaptchaResponse;
  }


  public LoginByUsernameRequest username(@javax.annotation.Nonnull String username) {
    this.username = username;
    return this;
  }

  /**
   * The Username of the User
   * @return username
   */
  @javax.annotation.Nonnull
  public String getUsername() {
    return username;
  }

  public void setUsername(@javax.annotation.Nonnull String username) {
    this.username = username;
  }


  public LoginByUsernameRequest password(@javax.annotation.Nonnull String password) {
    this.password = password;
    return this;
  }

  /**
   * The Password of the User
   * @return password
   */
  @javax.annotation.Nonnull
  public String getPassword() {
    return password;
  }

  public void setPassword(@javax.annotation.Nonnull String password) {
    this.password = password;
  }


  public LoginByUsernameRequest securityAnswer(@javax.annotation.Nullable String securityAnswer) {
    this.securityAnswer = securityAnswer;
    return this;
  }

  /**
   * The security answer which is set for the User, this will be used when the User is blocked for the security question.
   * @return securityAnswer
   */
  @javax.annotation.Nullable
  public String getSecurityAnswer() {
    return securityAnswer;
  }

  public void setSecurityAnswer(@javax.annotation.Nullable String securityAnswer) {
    this.securityAnswer = securityAnswer;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the LoginByUsernameRequest instance itself
   */
  public LoginByUsernameRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginByUsernameRequest loginByUsernameRequest = (LoginByUsernameRequest) o;
    return Objects.equals(this.gRecaptchaResponse, loginByUsernameRequest.gRecaptchaResponse) &&
        Objects.equals(this.qqCaptchaTicket, loginByUsernameRequest.qqCaptchaTicket) &&
        Objects.equals(this.qqCaptchaRandstr, loginByUsernameRequest.qqCaptchaRandstr) &&
        Objects.equals(this.hCaptchaResponse, loginByUsernameRequest.hCaptchaResponse) &&
        Objects.equals(this.username, loginByUsernameRequest.username) &&
        Objects.equals(this.password, loginByUsernameRequest.password) &&
        Objects.equals(this.securityAnswer, loginByUsernameRequest.securityAnswer)&&
        Objects.equals(this.additionalProperties, loginByUsernameRequest.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(gRecaptchaResponse, qqCaptchaTicket, qqCaptchaRandstr, hCaptchaResponse, username, password, securityAnswer, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginByUsernameRequest {\n");
    sb.append("    gRecaptchaResponse: ").append(toIndentedString(gRecaptchaResponse)).append("\n");
    sb.append("    qqCaptchaTicket: ").append(toIndentedString(qqCaptchaTicket)).append("\n");
    sb.append("    qqCaptchaRandstr: ").append(toIndentedString(qqCaptchaRandstr)).append("\n");
    sb.append("    hCaptchaResponse: ").append(toIndentedString(hCaptchaResponse)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    password: ").append("*").append("\n");
    sb.append("    securityAnswer: ").append(toIndentedString(securityAnswer)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("g-recaptcha-response");
    openapiFields.add("qq_captcha_ticket");
    openapiFields.add("qq_captcha_randstr");
    openapiFields.add("h-captcha-response");
    openapiFields.add("username");
    openapiFields.add("password");
    openapiFields.add("securityAnswer");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("username");
    openapiRequiredFields.add("password");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to LoginByUsernameRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!LoginByUsernameRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in LoginByUsernameRequest is not found in the empty JSON string", LoginByUsernameRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : LoginByUsernameRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("g-recaptcha-response") != null && !jsonObj.get("g-recaptcha-response").isJsonNull()) && !jsonObj.get("g-recaptcha-response").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `g-recaptcha-response` to be a primitive type in the JSON string but got `%s`", jsonObj.get("g-recaptcha-response").toString()));
      }
      if ((jsonObj.get("qq_captcha_ticket") != null && !jsonObj.get("qq_captcha_ticket").isJsonNull()) && !jsonObj.get("qq_captcha_ticket").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `qq_captcha_ticket` to be a primitive type in the JSON string but got `%s`", jsonObj.get("qq_captcha_ticket").toString()));
      }
      if ((jsonObj.get("qq_captcha_randstr") != null && !jsonObj.get("qq_captcha_randstr").isJsonNull()) && !jsonObj.get("qq_captcha_randstr").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `qq_captcha_randstr` to be a primitive type in the JSON string but got `%s`", jsonObj.get("qq_captcha_randstr").toString()));
      }
      if ((jsonObj.get("h-captcha-response") != null && !jsonObj.get("h-captcha-response").isJsonNull()) && !jsonObj.get("h-captcha-response").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `h-captcha-response` to be a primitive type in the JSON string but got `%s`", jsonObj.get("h-captcha-response").toString()));
      }
      if (!jsonObj.get("username").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `username` to be a primitive type in the JSON string but got `%s`", jsonObj.get("username").toString()));
      }
      if (!jsonObj.get("password").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `password` to be a primitive type in the JSON string but got `%s`", jsonObj.get("password").toString()));
      }
      if ((jsonObj.get("securityAnswer") != null && !jsonObj.get("securityAnswer").isJsonNull()) && !jsonObj.get("securityAnswer").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `securityAnswer` to be a primitive type in the JSON string but got `%s`", jsonObj.get("securityAnswer").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LoginByUsernameRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LoginByUsernameRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LoginByUsernameRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LoginByUsernameRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<LoginByUsernameRequest>() {
           @Override
           public void write(JsonWriter out, LoginByUsernameRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public LoginByUsernameRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             LoginByUsernameRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of LoginByUsernameRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of LoginByUsernameRequest
   * @throws IOException if the JSON string is invalid with respect to LoginByUsernameRequest
   */
  public static LoginByUsernameRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LoginByUsernameRequest.class);
  }

  /**
   * Convert an instance of LoginByUsernameRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

