/*
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.loginradius.sdk.internal.openapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.loginradius.sdk.internal.openapi.JSON;

/**
 * OIDC Discovery Config Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class OIDCDiscoveryResponse {
  public static final String SERIALIZED_NAME_ACR_VALUES_SUPPORTED = "acr_values_supported";
  @SerializedName(SERIALIZED_NAME_ACR_VALUES_SUPPORTED)
  @javax.annotation.Nullable
  private List<String> acrValuesSupported = new ArrayList<>();

  public static final String SERIALIZED_NAME_AUTHORIZATION_ENDPOINT = "authorization_endpoint";
  @SerializedName(SERIALIZED_NAME_AUTHORIZATION_ENDPOINT)
  @javax.annotation.Nullable
  private String authorizationEndpoint;

  public static final String SERIALIZED_NAME_BACKCHANNEL_LOGOUT_SESSION_SUPPORTED = "backchannel_logout_session_supported";
  @SerializedName(SERIALIZED_NAME_BACKCHANNEL_LOGOUT_SESSION_SUPPORTED)
  @javax.annotation.Nullable
  private Boolean backchannelLogoutSessionSupported;

  public static final String SERIALIZED_NAME_BACKCHANNEL_LOGOUT_SUPPORTED = "backchannel_logout_supported";
  @SerializedName(SERIALIZED_NAME_BACKCHANNEL_LOGOUT_SUPPORTED)
  @javax.annotation.Nullable
  private Boolean backchannelLogoutSupported;

  public static final String SERIALIZED_NAME_CLAIMS_SUPPORTED = "claims_supported";
  @SerializedName(SERIALIZED_NAME_CLAIMS_SUPPORTED)
  @javax.annotation.Nullable
  private List<String> claimsSupported = new ArrayList<>();

  public static final String SERIALIZED_NAME_CODE_CHALLENGE_METHODS_SUPPORTED = "code_challenge_methods_supported";
  @SerializedName(SERIALIZED_NAME_CODE_CHALLENGE_METHODS_SUPPORTED)
  @javax.annotation.Nullable
  private List<String> codeChallengeMethodsSupported = new ArrayList<>();

  public static final String SERIALIZED_NAME_END_SESSION_ENDPOINT = "end_session_endpoint";
  @SerializedName(SERIALIZED_NAME_END_SESSION_ENDPOINT)
  @javax.annotation.Nullable
  private String endSessionEndpoint;

  public static final String SERIALIZED_NAME_GRANT_TYPES_SUPPORTED = "grant_types_supported";
  @SerializedName(SERIALIZED_NAME_GRANT_TYPES_SUPPORTED)
  @javax.annotation.Nullable
  private List<String> grantTypesSupported = new ArrayList<>();

  public static final String SERIALIZED_NAME_ID_TOKEN_SIGNING_ALG_VALUES_SUPPORTED = "id_token_signing_alg_values_supported";
  @SerializedName(SERIALIZED_NAME_ID_TOKEN_SIGNING_ALG_VALUES_SUPPORTED)
  @javax.annotation.Nullable
  private List<String> idTokenSigningAlgValuesSupported = new ArrayList<>();

  public static final String SERIALIZED_NAME_ISSUER = "issuer";
  @SerializedName(SERIALIZED_NAME_ISSUER)
  @javax.annotation.Nullable
  private String issuer;

  public static final String SERIALIZED_NAME_JWKS_URI = "jwks_uri";
  @SerializedName(SERIALIZED_NAME_JWKS_URI)
  @javax.annotation.Nullable
  private String jwksUri;

  public static final String SERIALIZED_NAME_REQUEST_PARAMETER_SUPPORTED = "request_parameter_supported";
  @SerializedName(SERIALIZED_NAME_REQUEST_PARAMETER_SUPPORTED)
  @javax.annotation.Nullable
  private Boolean requestParameterSupported;

  public static final String SERIALIZED_NAME_RESPONSE_MODES_SUPPORTED = "response_modes_supported";
  @SerializedName(SERIALIZED_NAME_RESPONSE_MODES_SUPPORTED)
  @javax.annotation.Nullable
  private List<String> responseModesSupported = new ArrayList<>();

  public static final String SERIALIZED_NAME_RESPONSE_TYPES_SUPPORTED = "response_types_supported";
  @SerializedName(SERIALIZED_NAME_RESPONSE_TYPES_SUPPORTED)
  @javax.annotation.Nullable
  private List<String> responseTypesSupported = new ArrayList<>();

  public static final String SERIALIZED_NAME_REVOCATION_ENDPOINT = "revocation_endpoint";
  @SerializedName(SERIALIZED_NAME_REVOCATION_ENDPOINT)
  @javax.annotation.Nullable
  private String revocationEndpoint;

  public static final String SERIALIZED_NAME_INTROSPECTION_ENDPOINT = "introspection_endpoint";
  @SerializedName(SERIALIZED_NAME_INTROSPECTION_ENDPOINT)
  @javax.annotation.Nullable
  private String introspectionEndpoint;

  public static final String SERIALIZED_NAME_REVOCATION_ENDPOINT_AUTH_METHODS_SUPPORTED = "revocation_endpoint_auth_methods_supported";
  @SerializedName(SERIALIZED_NAME_REVOCATION_ENDPOINT_AUTH_METHODS_SUPPORTED)
  @javax.annotation.Nullable
  private List<String> revocationEndpointAuthMethodsSupported = new ArrayList<>();

  public static final String SERIALIZED_NAME_SCOPES_SUPPORTED = "scopes_supported";
  @SerializedName(SERIALIZED_NAME_SCOPES_SUPPORTED)
  @javax.annotation.Nullable
  private List<String> scopesSupported = new ArrayList<>();

  public static final String SERIALIZED_NAME_SUBJECT_TYPES_SUPPORTED = "subject_types_supported";
  @SerializedName(SERIALIZED_NAME_SUBJECT_TYPES_SUPPORTED)
  @javax.annotation.Nullable
  private List<String> subjectTypesSupported = new ArrayList<>();

  public static final String SERIALIZED_NAME_TOKEN_ENDPOINT = "token_endpoint";
  @SerializedName(SERIALIZED_NAME_TOKEN_ENDPOINT)
  @javax.annotation.Nullable
  private String tokenEndpoint;

  public static final String SERIALIZED_NAME_TOKEN_ENDPOINT_AUTH_METHODS_SUPPORTED = "token_endpoint_auth_methods_supported";
  @SerializedName(SERIALIZED_NAME_TOKEN_ENDPOINT_AUTH_METHODS_SUPPORTED)
  @javax.annotation.Nullable
  private List<String> tokenEndpointAuthMethodsSupported = new ArrayList<>();

  public static final String SERIALIZED_NAME_USERINFO_ENDPOINT = "userinfo_endpoint";
  @SerializedName(SERIALIZED_NAME_USERINFO_ENDPOINT)
  @javax.annotation.Nullable
  private String userinfoEndpoint;

  public OIDCDiscoveryResponse() {
  }

  public OIDCDiscoveryResponse acrValuesSupported(@javax.annotation.Nullable List<String> acrValuesSupported) {
    this.acrValuesSupported = acrValuesSupported;
    return this;
  }

  public OIDCDiscoveryResponse addAcrValuesSupportedItem(String acrValuesSupportedItem) {
    if (this.acrValuesSupported == null) {
      this.acrValuesSupported = new ArrayList<>();
    }
    this.acrValuesSupported.add(acrValuesSupportedItem);
    return this;
  }

  /**
   * Get acrValuesSupported
   * @return acrValuesSupported
   */
  @javax.annotation.Nullable
  public List<String> getAcrValuesSupported() {
    return acrValuesSupported;
  }

  public void setAcrValuesSupported(@javax.annotation.Nullable List<String> acrValuesSupported) {
    this.acrValuesSupported = acrValuesSupported;
  }


  public OIDCDiscoveryResponse authorizationEndpoint(@javax.annotation.Nullable String authorizationEndpoint) {
    this.authorizationEndpoint = authorizationEndpoint;
    return this;
  }

  /**
   * Get authorizationEndpoint
   * @return authorizationEndpoint
   */
  @javax.annotation.Nullable
  public String getAuthorizationEndpoint() {
    return authorizationEndpoint;
  }

  public void setAuthorizationEndpoint(@javax.annotation.Nullable String authorizationEndpoint) {
    this.authorizationEndpoint = authorizationEndpoint;
  }


  public OIDCDiscoveryResponse backchannelLogoutSessionSupported(@javax.annotation.Nullable Boolean backchannelLogoutSessionSupported) {
    this.backchannelLogoutSessionSupported = backchannelLogoutSessionSupported;
    return this;
  }

  /**
   * Get backchannelLogoutSessionSupported
   * @return backchannelLogoutSessionSupported
   */
  @javax.annotation.Nullable
  public Boolean getBackchannelLogoutSessionSupported() {
    return backchannelLogoutSessionSupported;
  }

  public void setBackchannelLogoutSessionSupported(@javax.annotation.Nullable Boolean backchannelLogoutSessionSupported) {
    this.backchannelLogoutSessionSupported = backchannelLogoutSessionSupported;
  }


  public OIDCDiscoveryResponse backchannelLogoutSupported(@javax.annotation.Nullable Boolean backchannelLogoutSupported) {
    this.backchannelLogoutSupported = backchannelLogoutSupported;
    return this;
  }

  /**
   * Get backchannelLogoutSupported
   * @return backchannelLogoutSupported
   */
  @javax.annotation.Nullable
  public Boolean getBackchannelLogoutSupported() {
    return backchannelLogoutSupported;
  }

  public void setBackchannelLogoutSupported(@javax.annotation.Nullable Boolean backchannelLogoutSupported) {
    this.backchannelLogoutSupported = backchannelLogoutSupported;
  }


  public OIDCDiscoveryResponse claimsSupported(@javax.annotation.Nullable List<String> claimsSupported) {
    this.claimsSupported = claimsSupported;
    return this;
  }

  public OIDCDiscoveryResponse addClaimsSupportedItem(String claimsSupportedItem) {
    if (this.claimsSupported == null) {
      this.claimsSupported = new ArrayList<>();
    }
    this.claimsSupported.add(claimsSupportedItem);
    return this;
  }

  /**
   * Get claimsSupported
   * @return claimsSupported
   */
  @javax.annotation.Nullable
  public List<String> getClaimsSupported() {
    return claimsSupported;
  }

  public void setClaimsSupported(@javax.annotation.Nullable List<String> claimsSupported) {
    this.claimsSupported = claimsSupported;
  }


  public OIDCDiscoveryResponse codeChallengeMethodsSupported(@javax.annotation.Nullable List<String> codeChallengeMethodsSupported) {
    this.codeChallengeMethodsSupported = codeChallengeMethodsSupported;
    return this;
  }

  public OIDCDiscoveryResponse addCodeChallengeMethodsSupportedItem(String codeChallengeMethodsSupportedItem) {
    if (this.codeChallengeMethodsSupported == null) {
      this.codeChallengeMethodsSupported = new ArrayList<>();
    }
    this.codeChallengeMethodsSupported.add(codeChallengeMethodsSupportedItem);
    return this;
  }

  /**
   * Get codeChallengeMethodsSupported
   * @return codeChallengeMethodsSupported
   */
  @javax.annotation.Nullable
  public List<String> getCodeChallengeMethodsSupported() {
    return codeChallengeMethodsSupported;
  }

  public void setCodeChallengeMethodsSupported(@javax.annotation.Nullable List<String> codeChallengeMethodsSupported) {
    this.codeChallengeMethodsSupported = codeChallengeMethodsSupported;
  }


  public OIDCDiscoveryResponse endSessionEndpoint(@javax.annotation.Nullable String endSessionEndpoint) {
    this.endSessionEndpoint = endSessionEndpoint;
    return this;
  }

  /**
   * Get endSessionEndpoint
   * @return endSessionEndpoint
   */
  @javax.annotation.Nullable
  public String getEndSessionEndpoint() {
    return endSessionEndpoint;
  }

  public void setEndSessionEndpoint(@javax.annotation.Nullable String endSessionEndpoint) {
    this.endSessionEndpoint = endSessionEndpoint;
  }


  public OIDCDiscoveryResponse grantTypesSupported(@javax.annotation.Nullable List<String> grantTypesSupported) {
    this.grantTypesSupported = grantTypesSupported;
    return this;
  }

  public OIDCDiscoveryResponse addGrantTypesSupportedItem(String grantTypesSupportedItem) {
    if (this.grantTypesSupported == null) {
      this.grantTypesSupported = new ArrayList<>();
    }
    this.grantTypesSupported.add(grantTypesSupportedItem);
    return this;
  }

  /**
   * Get grantTypesSupported
   * @return grantTypesSupported
   */
  @javax.annotation.Nullable
  public List<String> getGrantTypesSupported() {
    return grantTypesSupported;
  }

  public void setGrantTypesSupported(@javax.annotation.Nullable List<String> grantTypesSupported) {
    this.grantTypesSupported = grantTypesSupported;
  }


  public OIDCDiscoveryResponse idTokenSigningAlgValuesSupported(@javax.annotation.Nullable List<String> idTokenSigningAlgValuesSupported) {
    this.idTokenSigningAlgValuesSupported = idTokenSigningAlgValuesSupported;
    return this;
  }

  public OIDCDiscoveryResponse addIdTokenSigningAlgValuesSupportedItem(String idTokenSigningAlgValuesSupportedItem) {
    if (this.idTokenSigningAlgValuesSupported == null) {
      this.idTokenSigningAlgValuesSupported = new ArrayList<>();
    }
    this.idTokenSigningAlgValuesSupported.add(idTokenSigningAlgValuesSupportedItem);
    return this;
  }

  /**
   * Get idTokenSigningAlgValuesSupported
   * @return idTokenSigningAlgValuesSupported
   */
  @javax.annotation.Nullable
  public List<String> getIdTokenSigningAlgValuesSupported() {
    return idTokenSigningAlgValuesSupported;
  }

  public void setIdTokenSigningAlgValuesSupported(@javax.annotation.Nullable List<String> idTokenSigningAlgValuesSupported) {
    this.idTokenSigningAlgValuesSupported = idTokenSigningAlgValuesSupported;
  }


  public OIDCDiscoveryResponse issuer(@javax.annotation.Nullable String issuer) {
    this.issuer = issuer;
    return this;
  }

  /**
   * Get issuer
   * @return issuer
   */
  @javax.annotation.Nullable
  public String getIssuer() {
    return issuer;
  }

  public void setIssuer(@javax.annotation.Nullable String issuer) {
    this.issuer = issuer;
  }


  public OIDCDiscoveryResponse jwksUri(@javax.annotation.Nullable String jwksUri) {
    this.jwksUri = jwksUri;
    return this;
  }

  /**
   * Get jwksUri
   * @return jwksUri
   */
  @javax.annotation.Nullable
  public String getJwksUri() {
    return jwksUri;
  }

  public void setJwksUri(@javax.annotation.Nullable String jwksUri) {
    this.jwksUri = jwksUri;
  }


  public OIDCDiscoveryResponse requestParameterSupported(@javax.annotation.Nullable Boolean requestParameterSupported) {
    this.requestParameterSupported = requestParameterSupported;
    return this;
  }

  /**
   * Get requestParameterSupported
   * @return requestParameterSupported
   */
  @javax.annotation.Nullable
  public Boolean getRequestParameterSupported() {
    return requestParameterSupported;
  }

  public void setRequestParameterSupported(@javax.annotation.Nullable Boolean requestParameterSupported) {
    this.requestParameterSupported = requestParameterSupported;
  }


  public OIDCDiscoveryResponse responseModesSupported(@javax.annotation.Nullable List<String> responseModesSupported) {
    this.responseModesSupported = responseModesSupported;
    return this;
  }

  public OIDCDiscoveryResponse addResponseModesSupportedItem(String responseModesSupportedItem) {
    if (this.responseModesSupported == null) {
      this.responseModesSupported = new ArrayList<>();
    }
    this.responseModesSupported.add(responseModesSupportedItem);
    return this;
  }

  /**
   * Get responseModesSupported
   * @return responseModesSupported
   */
  @javax.annotation.Nullable
  public List<String> getResponseModesSupported() {
    return responseModesSupported;
  }

  public void setResponseModesSupported(@javax.annotation.Nullable List<String> responseModesSupported) {
    this.responseModesSupported = responseModesSupported;
  }


  public OIDCDiscoveryResponse responseTypesSupported(@javax.annotation.Nullable List<String> responseTypesSupported) {
    this.responseTypesSupported = responseTypesSupported;
    return this;
  }

  public OIDCDiscoveryResponse addResponseTypesSupportedItem(String responseTypesSupportedItem) {
    if (this.responseTypesSupported == null) {
      this.responseTypesSupported = new ArrayList<>();
    }
    this.responseTypesSupported.add(responseTypesSupportedItem);
    return this;
  }

  /**
   * Get responseTypesSupported
   * @return responseTypesSupported
   */
  @javax.annotation.Nullable
  public List<String> getResponseTypesSupported() {
    return responseTypesSupported;
  }

  public void setResponseTypesSupported(@javax.annotation.Nullable List<String> responseTypesSupported) {
    this.responseTypesSupported = responseTypesSupported;
  }


  public OIDCDiscoveryResponse revocationEndpoint(@javax.annotation.Nullable String revocationEndpoint) {
    this.revocationEndpoint = revocationEndpoint;
    return this;
  }

  /**
   * Get revocationEndpoint
   * @return revocationEndpoint
   */
  @javax.annotation.Nullable
  public String getRevocationEndpoint() {
    return revocationEndpoint;
  }

  public void setRevocationEndpoint(@javax.annotation.Nullable String revocationEndpoint) {
    this.revocationEndpoint = revocationEndpoint;
  }


  public OIDCDiscoveryResponse introspectionEndpoint(@javax.annotation.Nullable String introspectionEndpoint) {
    this.introspectionEndpoint = introspectionEndpoint;
    return this;
  }

  /**
   * OAuth 2.0 Token Introspection endpoint (RFC 7662)
   * @return introspectionEndpoint
   */
  @javax.annotation.Nullable
  public String getIntrospectionEndpoint() {
    return introspectionEndpoint;
  }

  public void setIntrospectionEndpoint(@javax.annotation.Nullable String introspectionEndpoint) {
    this.introspectionEndpoint = introspectionEndpoint;
  }


  public OIDCDiscoveryResponse revocationEndpointAuthMethodsSupported(@javax.annotation.Nullable List<String> revocationEndpointAuthMethodsSupported) {
    this.revocationEndpointAuthMethodsSupported = revocationEndpointAuthMethodsSupported;
    return this;
  }

  public OIDCDiscoveryResponse addRevocationEndpointAuthMethodsSupportedItem(String revocationEndpointAuthMethodsSupportedItem) {
    if (this.revocationEndpointAuthMethodsSupported == null) {
      this.revocationEndpointAuthMethodsSupported = new ArrayList<>();
    }
    this.revocationEndpointAuthMethodsSupported.add(revocationEndpointAuthMethodsSupportedItem);
    return this;
  }

  /**
   * Get revocationEndpointAuthMethodsSupported
   * @return revocationEndpointAuthMethodsSupported
   */
  @javax.annotation.Nullable
  public List<String> getRevocationEndpointAuthMethodsSupported() {
    return revocationEndpointAuthMethodsSupported;
  }

  public void setRevocationEndpointAuthMethodsSupported(@javax.annotation.Nullable List<String> revocationEndpointAuthMethodsSupported) {
    this.revocationEndpointAuthMethodsSupported = revocationEndpointAuthMethodsSupported;
  }


  public OIDCDiscoveryResponse scopesSupported(@javax.annotation.Nullable List<String> scopesSupported) {
    this.scopesSupported = scopesSupported;
    return this;
  }

  public OIDCDiscoveryResponse addScopesSupportedItem(String scopesSupportedItem) {
    if (this.scopesSupported == null) {
      this.scopesSupported = new ArrayList<>();
    }
    this.scopesSupported.add(scopesSupportedItem);
    return this;
  }

  /**
   * Get scopesSupported
   * @return scopesSupported
   */
  @javax.annotation.Nullable
  public List<String> getScopesSupported() {
    return scopesSupported;
  }

  public void setScopesSupported(@javax.annotation.Nullable List<String> scopesSupported) {
    this.scopesSupported = scopesSupported;
  }


  public OIDCDiscoveryResponse subjectTypesSupported(@javax.annotation.Nullable List<String> subjectTypesSupported) {
    this.subjectTypesSupported = subjectTypesSupported;
    return this;
  }

  public OIDCDiscoveryResponse addSubjectTypesSupportedItem(String subjectTypesSupportedItem) {
    if (this.subjectTypesSupported == null) {
      this.subjectTypesSupported = new ArrayList<>();
    }
    this.subjectTypesSupported.add(subjectTypesSupportedItem);
    return this;
  }

  /**
   * Get subjectTypesSupported
   * @return subjectTypesSupported
   */
  @javax.annotation.Nullable
  public List<String> getSubjectTypesSupported() {
    return subjectTypesSupported;
  }

  public void setSubjectTypesSupported(@javax.annotation.Nullable List<String> subjectTypesSupported) {
    this.subjectTypesSupported = subjectTypesSupported;
  }


  public OIDCDiscoveryResponse tokenEndpoint(@javax.annotation.Nullable String tokenEndpoint) {
    this.tokenEndpoint = tokenEndpoint;
    return this;
  }

  /**
   * Get tokenEndpoint
   * @return tokenEndpoint
   */
  @javax.annotation.Nullable
  public String getTokenEndpoint() {
    return tokenEndpoint;
  }

  public void setTokenEndpoint(@javax.annotation.Nullable String tokenEndpoint) {
    this.tokenEndpoint = tokenEndpoint;
  }


  public OIDCDiscoveryResponse tokenEndpointAuthMethodsSupported(@javax.annotation.Nullable List<String> tokenEndpointAuthMethodsSupported) {
    this.tokenEndpointAuthMethodsSupported = tokenEndpointAuthMethodsSupported;
    return this;
  }

  public OIDCDiscoveryResponse addTokenEndpointAuthMethodsSupportedItem(String tokenEndpointAuthMethodsSupportedItem) {
    if (this.tokenEndpointAuthMethodsSupported == null) {
      this.tokenEndpointAuthMethodsSupported = new ArrayList<>();
    }
    this.tokenEndpointAuthMethodsSupported.add(tokenEndpointAuthMethodsSupportedItem);
    return this;
  }

  /**
   * Get tokenEndpointAuthMethodsSupported
   * @return tokenEndpointAuthMethodsSupported
   */
  @javax.annotation.Nullable
  public List<String> getTokenEndpointAuthMethodsSupported() {
    return tokenEndpointAuthMethodsSupported;
  }

  public void setTokenEndpointAuthMethodsSupported(@javax.annotation.Nullable List<String> tokenEndpointAuthMethodsSupported) {
    this.tokenEndpointAuthMethodsSupported = tokenEndpointAuthMethodsSupported;
  }


  public OIDCDiscoveryResponse userinfoEndpoint(@javax.annotation.Nullable String userinfoEndpoint) {
    this.userinfoEndpoint = userinfoEndpoint;
    return this;
  }

  /**
   * Get userinfoEndpoint
   * @return userinfoEndpoint
   */
  @javax.annotation.Nullable
  public String getUserinfoEndpoint() {
    return userinfoEndpoint;
  }

  public void setUserinfoEndpoint(@javax.annotation.Nullable String userinfoEndpoint) {
    this.userinfoEndpoint = userinfoEndpoint;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the OIDCDiscoveryResponse instance itself
   */
  public OIDCDiscoveryResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OIDCDiscoveryResponse oiDCDiscoveryResponse = (OIDCDiscoveryResponse) o;
    return Objects.equals(this.acrValuesSupported, oiDCDiscoveryResponse.acrValuesSupported) &&
        Objects.equals(this.authorizationEndpoint, oiDCDiscoveryResponse.authorizationEndpoint) &&
        Objects.equals(this.backchannelLogoutSessionSupported, oiDCDiscoveryResponse.backchannelLogoutSessionSupported) &&
        Objects.equals(this.backchannelLogoutSupported, oiDCDiscoveryResponse.backchannelLogoutSupported) &&
        Objects.equals(this.claimsSupported, oiDCDiscoveryResponse.claimsSupported) &&
        Objects.equals(this.codeChallengeMethodsSupported, oiDCDiscoveryResponse.codeChallengeMethodsSupported) &&
        Objects.equals(this.endSessionEndpoint, oiDCDiscoveryResponse.endSessionEndpoint) &&
        Objects.equals(this.grantTypesSupported, oiDCDiscoveryResponse.grantTypesSupported) &&
        Objects.equals(this.idTokenSigningAlgValuesSupported, oiDCDiscoveryResponse.idTokenSigningAlgValuesSupported) &&
        Objects.equals(this.issuer, oiDCDiscoveryResponse.issuer) &&
        Objects.equals(this.jwksUri, oiDCDiscoveryResponse.jwksUri) &&
        Objects.equals(this.requestParameterSupported, oiDCDiscoveryResponse.requestParameterSupported) &&
        Objects.equals(this.responseModesSupported, oiDCDiscoveryResponse.responseModesSupported) &&
        Objects.equals(this.responseTypesSupported, oiDCDiscoveryResponse.responseTypesSupported) &&
        Objects.equals(this.revocationEndpoint, oiDCDiscoveryResponse.revocationEndpoint) &&
        Objects.equals(this.introspectionEndpoint, oiDCDiscoveryResponse.introspectionEndpoint) &&
        Objects.equals(this.revocationEndpointAuthMethodsSupported, oiDCDiscoveryResponse.revocationEndpointAuthMethodsSupported) &&
        Objects.equals(this.scopesSupported, oiDCDiscoveryResponse.scopesSupported) &&
        Objects.equals(this.subjectTypesSupported, oiDCDiscoveryResponse.subjectTypesSupported) &&
        Objects.equals(this.tokenEndpoint, oiDCDiscoveryResponse.tokenEndpoint) &&
        Objects.equals(this.tokenEndpointAuthMethodsSupported, oiDCDiscoveryResponse.tokenEndpointAuthMethodsSupported) &&
        Objects.equals(this.userinfoEndpoint, oiDCDiscoveryResponse.userinfoEndpoint)&&
        Objects.equals(this.additionalProperties, oiDCDiscoveryResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acrValuesSupported, authorizationEndpoint, backchannelLogoutSessionSupported, backchannelLogoutSupported, claimsSupported, codeChallengeMethodsSupported, endSessionEndpoint, grantTypesSupported, idTokenSigningAlgValuesSupported, issuer, jwksUri, requestParameterSupported, responseModesSupported, responseTypesSupported, revocationEndpoint, introspectionEndpoint, revocationEndpointAuthMethodsSupported, scopesSupported, subjectTypesSupported, tokenEndpoint, tokenEndpointAuthMethodsSupported, userinfoEndpoint, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OIDCDiscoveryResponse {\n");
    sb.append("    acrValuesSupported: ").append(toIndentedString(acrValuesSupported)).append("\n");
    sb.append("    authorizationEndpoint: ").append(toIndentedString(authorizationEndpoint)).append("\n");
    sb.append("    backchannelLogoutSessionSupported: ").append(toIndentedString(backchannelLogoutSessionSupported)).append("\n");
    sb.append("    backchannelLogoutSupported: ").append(toIndentedString(backchannelLogoutSupported)).append("\n");
    sb.append("    claimsSupported: ").append(toIndentedString(claimsSupported)).append("\n");
    sb.append("    codeChallengeMethodsSupported: ").append(toIndentedString(codeChallengeMethodsSupported)).append("\n");
    sb.append("    endSessionEndpoint: ").append(toIndentedString(endSessionEndpoint)).append("\n");
    sb.append("    grantTypesSupported: ").append(toIndentedString(grantTypesSupported)).append("\n");
    sb.append("    idTokenSigningAlgValuesSupported: ").append(toIndentedString(idTokenSigningAlgValuesSupported)).append("\n");
    sb.append("    issuer: ").append(toIndentedString(issuer)).append("\n");
    sb.append("    jwksUri: ").append(toIndentedString(jwksUri)).append("\n");
    sb.append("    requestParameterSupported: ").append(toIndentedString(requestParameterSupported)).append("\n");
    sb.append("    responseModesSupported: ").append(toIndentedString(responseModesSupported)).append("\n");
    sb.append("    responseTypesSupported: ").append(toIndentedString(responseTypesSupported)).append("\n");
    sb.append("    revocationEndpoint: ").append(toIndentedString(revocationEndpoint)).append("\n");
    sb.append("    introspectionEndpoint: ").append(toIndentedString(introspectionEndpoint)).append("\n");
    sb.append("    revocationEndpointAuthMethodsSupported: ").append(toIndentedString(revocationEndpointAuthMethodsSupported)).append("\n");
    sb.append("    scopesSupported: ").append(toIndentedString(scopesSupported)).append("\n");
    sb.append("    subjectTypesSupported: ").append(toIndentedString(subjectTypesSupported)).append("\n");
    sb.append("    tokenEndpoint: ").append(toIndentedString(tokenEndpoint)).append("\n");
    sb.append("    tokenEndpointAuthMethodsSupported: ").append(toIndentedString(tokenEndpointAuthMethodsSupported)).append("\n");
    sb.append("    userinfoEndpoint: ").append(toIndentedString(userinfoEndpoint)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("acr_values_supported");
    openapiFields.add("authorization_endpoint");
    openapiFields.add("backchannel_logout_session_supported");
    openapiFields.add("backchannel_logout_supported");
    openapiFields.add("claims_supported");
    openapiFields.add("code_challenge_methods_supported");
    openapiFields.add("end_session_endpoint");
    openapiFields.add("grant_types_supported");
    openapiFields.add("id_token_signing_alg_values_supported");
    openapiFields.add("issuer");
    openapiFields.add("jwks_uri");
    openapiFields.add("request_parameter_supported");
    openapiFields.add("response_modes_supported");
    openapiFields.add("response_types_supported");
    openapiFields.add("revocation_endpoint");
    openapiFields.add("introspection_endpoint");
    openapiFields.add("revocation_endpoint_auth_methods_supported");
    openapiFields.add("scopes_supported");
    openapiFields.add("subject_types_supported");
    openapiFields.add("token_endpoint");
    openapiFields.add("token_endpoint_auth_methods_supported");
    openapiFields.add("userinfo_endpoint");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to OIDCDiscoveryResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OIDCDiscoveryResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OIDCDiscoveryResponse is not found in the empty JSON string", OIDCDiscoveryResponse.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("acr_values_supported") != null && !jsonObj.get("acr_values_supported").isJsonNull() && !jsonObj.get("acr_values_supported").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `acr_values_supported` to be an array in the JSON string but got `%s`", jsonObj.get("acr_values_supported").toString()));
      }
      if ((jsonObj.get("authorization_endpoint") != null && !jsonObj.get("authorization_endpoint").isJsonNull()) && !jsonObj.get("authorization_endpoint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `authorization_endpoint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("authorization_endpoint").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("claims_supported") != null && !jsonObj.get("claims_supported").isJsonNull() && !jsonObj.get("claims_supported").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `claims_supported` to be an array in the JSON string but got `%s`", jsonObj.get("claims_supported").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("code_challenge_methods_supported") != null && !jsonObj.get("code_challenge_methods_supported").isJsonNull() && !jsonObj.get("code_challenge_methods_supported").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `code_challenge_methods_supported` to be an array in the JSON string but got `%s`", jsonObj.get("code_challenge_methods_supported").toString()));
      }
      if ((jsonObj.get("end_session_endpoint") != null && !jsonObj.get("end_session_endpoint").isJsonNull()) && !jsonObj.get("end_session_endpoint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `end_session_endpoint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("end_session_endpoint").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("grant_types_supported") != null && !jsonObj.get("grant_types_supported").isJsonNull() && !jsonObj.get("grant_types_supported").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `grant_types_supported` to be an array in the JSON string but got `%s`", jsonObj.get("grant_types_supported").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("id_token_signing_alg_values_supported") != null && !jsonObj.get("id_token_signing_alg_values_supported").isJsonNull() && !jsonObj.get("id_token_signing_alg_values_supported").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `id_token_signing_alg_values_supported` to be an array in the JSON string but got `%s`", jsonObj.get("id_token_signing_alg_values_supported").toString()));
      }
      if ((jsonObj.get("issuer") != null && !jsonObj.get("issuer").isJsonNull()) && !jsonObj.get("issuer").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `issuer` to be a primitive type in the JSON string but got `%s`", jsonObj.get("issuer").toString()));
      }
      if ((jsonObj.get("jwks_uri") != null && !jsonObj.get("jwks_uri").isJsonNull()) && !jsonObj.get("jwks_uri").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `jwks_uri` to be a primitive type in the JSON string but got `%s`", jsonObj.get("jwks_uri").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("response_modes_supported") != null && !jsonObj.get("response_modes_supported").isJsonNull() && !jsonObj.get("response_modes_supported").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `response_modes_supported` to be an array in the JSON string but got `%s`", jsonObj.get("response_modes_supported").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("response_types_supported") != null && !jsonObj.get("response_types_supported").isJsonNull() && !jsonObj.get("response_types_supported").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `response_types_supported` to be an array in the JSON string but got `%s`", jsonObj.get("response_types_supported").toString()));
      }
      if ((jsonObj.get("revocation_endpoint") != null && !jsonObj.get("revocation_endpoint").isJsonNull()) && !jsonObj.get("revocation_endpoint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `revocation_endpoint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("revocation_endpoint").toString()));
      }
      if ((jsonObj.get("introspection_endpoint") != null && !jsonObj.get("introspection_endpoint").isJsonNull()) && !jsonObj.get("introspection_endpoint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `introspection_endpoint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("introspection_endpoint").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("revocation_endpoint_auth_methods_supported") != null && !jsonObj.get("revocation_endpoint_auth_methods_supported").isJsonNull() && !jsonObj.get("revocation_endpoint_auth_methods_supported").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `revocation_endpoint_auth_methods_supported` to be an array in the JSON string but got `%s`", jsonObj.get("revocation_endpoint_auth_methods_supported").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("scopes_supported") != null && !jsonObj.get("scopes_supported").isJsonNull() && !jsonObj.get("scopes_supported").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `scopes_supported` to be an array in the JSON string but got `%s`", jsonObj.get("scopes_supported").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("subject_types_supported") != null && !jsonObj.get("subject_types_supported").isJsonNull() && !jsonObj.get("subject_types_supported").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `subject_types_supported` to be an array in the JSON string but got `%s`", jsonObj.get("subject_types_supported").toString()));
      }
      if ((jsonObj.get("token_endpoint") != null && !jsonObj.get("token_endpoint").isJsonNull()) && !jsonObj.get("token_endpoint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `token_endpoint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("token_endpoint").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("token_endpoint_auth_methods_supported") != null && !jsonObj.get("token_endpoint_auth_methods_supported").isJsonNull() && !jsonObj.get("token_endpoint_auth_methods_supported").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `token_endpoint_auth_methods_supported` to be an array in the JSON string but got `%s`", jsonObj.get("token_endpoint_auth_methods_supported").toString()));
      }
      if ((jsonObj.get("userinfo_endpoint") != null && !jsonObj.get("userinfo_endpoint").isJsonNull()) && !jsonObj.get("userinfo_endpoint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `userinfo_endpoint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("userinfo_endpoint").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OIDCDiscoveryResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OIDCDiscoveryResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OIDCDiscoveryResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OIDCDiscoveryResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<OIDCDiscoveryResponse>() {
           @Override
           public void write(JsonWriter out, OIDCDiscoveryResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public OIDCDiscoveryResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             OIDCDiscoveryResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of OIDCDiscoveryResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OIDCDiscoveryResponse
   * @throws IOException if the JSON string is invalid with respect to OIDCDiscoveryResponse
   */
  public static OIDCDiscoveryResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OIDCDiscoveryResponse.class);
  }

  /**
   * Convert an instance of OIDCDiscoveryResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

