/*
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.loginradius.sdk.internal.openapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.loginradius.sdk.internal.openapi.JSON;

/**
 * Session policy for the organization
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class OrganizationsPolicyBaseSessionPolicy {
  public static final String SERIALIZED_NAME_ACCESS_TOKEN_T_T_L = "AccessTokenTTL";
  @SerializedName(SERIALIZED_NAME_ACCESS_TOKEN_T_T_L)
  @javax.annotation.Nullable
  private Integer accessTokenTTL;

  public static final String SERIALIZED_NAME_REFRESH_TOKEN_T_T_L = "RefreshTokenTTL";
  @SerializedName(SERIALIZED_NAME_REFRESH_TOKEN_T_T_L)
  @javax.annotation.Nullable
  private Integer refreshTokenTTL;

  public OrganizationsPolicyBaseSessionPolicy() {
  }

  public OrganizationsPolicyBaseSessionPolicy accessTokenTTL(@javax.annotation.Nullable Integer accessTokenTTL) {
    this.accessTokenTTL = accessTokenTTL;
    return this;
  }

  /**
   * Time-to-live (TTL) for Access Tokens in seconds
   * @return accessTokenTTL
   */
  @javax.annotation.Nullable
  public Integer getAccessTokenTTL() {
    return accessTokenTTL;
  }

  public void setAccessTokenTTL(@javax.annotation.Nullable Integer accessTokenTTL) {
    this.accessTokenTTL = accessTokenTTL;
  }


  public OrganizationsPolicyBaseSessionPolicy refreshTokenTTL(@javax.annotation.Nullable Integer refreshTokenTTL) {
    this.refreshTokenTTL = refreshTokenTTL;
    return this;
  }

  /**
   * Time-to-live (TTL) for refresh tokens in seconds
   * @return refreshTokenTTL
   */
  @javax.annotation.Nullable
  public Integer getRefreshTokenTTL() {
    return refreshTokenTTL;
  }

  public void setRefreshTokenTTL(@javax.annotation.Nullable Integer refreshTokenTTL) {
    this.refreshTokenTTL = refreshTokenTTL;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the OrganizationsPolicyBaseSessionPolicy instance itself
   */
  public OrganizationsPolicyBaseSessionPolicy putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganizationsPolicyBaseSessionPolicy organizationsPolicyBaseSessionPolicy = (OrganizationsPolicyBaseSessionPolicy) o;
    return Objects.equals(this.accessTokenTTL, organizationsPolicyBaseSessionPolicy.accessTokenTTL) &&
        Objects.equals(this.refreshTokenTTL, organizationsPolicyBaseSessionPolicy.refreshTokenTTL)&&
        Objects.equals(this.additionalProperties, organizationsPolicyBaseSessionPolicy.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessTokenTTL, refreshTokenTTL, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganizationsPolicyBaseSessionPolicy {\n");
    sb.append("    accessTokenTTL: ").append(toIndentedString(accessTokenTTL)).append("\n");
    sb.append("    refreshTokenTTL: ").append(toIndentedString(refreshTokenTTL)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("AccessTokenTTL");
    openapiFields.add("RefreshTokenTTL");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to OrganizationsPolicyBaseSessionPolicy
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OrganizationsPolicyBaseSessionPolicy.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OrganizationsPolicyBaseSessionPolicy is not found in the empty JSON string", OrganizationsPolicyBaseSessionPolicy.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OrganizationsPolicyBaseSessionPolicy.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OrganizationsPolicyBaseSessionPolicy' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OrganizationsPolicyBaseSessionPolicy> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OrganizationsPolicyBaseSessionPolicy.class));

       return (TypeAdapter<T>) new TypeAdapter<OrganizationsPolicyBaseSessionPolicy>() {
           @Override
           public void write(JsonWriter out, OrganizationsPolicyBaseSessionPolicy value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public OrganizationsPolicyBaseSessionPolicy read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             OrganizationsPolicyBaseSessionPolicy instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of OrganizationsPolicyBaseSessionPolicy given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OrganizationsPolicyBaseSessionPolicy
   * @throws IOException if the JSON string is invalid with respect to OrganizationsPolicyBaseSessionPolicy
   */
  public static OrganizationsPolicyBaseSessionPolicy fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OrganizationsPolicyBaseSessionPolicy.class);
  }

  /**
   * Convert an instance of OrganizationsPolicyBaseSessionPolicy to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

