/*
 * LoginRadius API
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.loginradius.sdk.internal.openapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.loginradius.sdk.internal.openapi.JSON;

/**
 * ProfileWithoutIdentitiesPIN
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class ProfileWithoutIdentitiesPIN {
  public static final String SERIALIZED_NAME_SKIPPED = "Skipped";
  @SerializedName(SERIALIZED_NAME_SKIPPED)
  @javax.annotation.Nullable
  private Boolean skipped;

  public static final String SERIALIZED_NAME_LAST_P_I_N_CHANGE_TOKEN = "LastPINChangeToken";
  @SerializedName(SERIALIZED_NAME_LAST_P_I_N_CHANGE_TOKEN)
  @javax.annotation.Nullable
  private String lastPINChangeToken;

  public static final String SERIALIZED_NAME_LAST_P_I_N_CHANGE_DATE = "LastPINChangeDate";
  @SerializedName(SERIALIZED_NAME_LAST_P_I_N_CHANGE_DATE)
  @javax.annotation.Nullable
  private OffsetDateTime lastPINChangeDate;

  public static final String SERIALIZED_NAME_SKIPPED_DATE = "SkippedDate";
  @SerializedName(SERIALIZED_NAME_SKIPPED_DATE)
  @javax.annotation.Nullable
  private OffsetDateTime skippedDate;

  public static final String SERIALIZED_NAME_PI_N_HASHING_CONFIG = "PINHashingConfig";
  @SerializedName(SERIALIZED_NAME_PI_N_HASHING_CONFIG)
  @javax.annotation.Nullable
  private String piNHashingConfig;

  public static final String SERIALIZED_NAME_P_I_N = "PIN";
  @SerializedName(SERIALIZED_NAME_P_I_N)
  @javax.annotation.Nullable
  private String PIN;

  public static final String SERIALIZED_NAME_IS_P_I_N_SET = "IsPINSet";
  @SerializedName(SERIALIZED_NAME_IS_P_I_N_SET)
  @javax.annotation.Nullable
  private Boolean isPINSet;

  public ProfileWithoutIdentitiesPIN() {
  }

  public ProfileWithoutIdentitiesPIN skipped(@javax.annotation.Nullable Boolean skipped) {
    this.skipped = skipped;
    return this;
  }

  /**
   * Get skipped
   * @return skipped
   */
  @javax.annotation.Nullable
  public Boolean getSkipped() {
    return skipped;
  }

  public void setSkipped(@javax.annotation.Nullable Boolean skipped) {
    this.skipped = skipped;
  }


  public ProfileWithoutIdentitiesPIN lastPINChangeToken(@javax.annotation.Nullable String lastPINChangeToken) {
    this.lastPINChangeToken = lastPINChangeToken;
    return this;
  }

  /**
   * Get lastPINChangeToken
   * @return lastPINChangeToken
   */
  @javax.annotation.Nullable
  public String getLastPINChangeToken() {
    return lastPINChangeToken;
  }

  public void setLastPINChangeToken(@javax.annotation.Nullable String lastPINChangeToken) {
    this.lastPINChangeToken = lastPINChangeToken;
  }


  public ProfileWithoutIdentitiesPIN lastPINChangeDate(@javax.annotation.Nullable OffsetDateTime lastPINChangeDate) {
    this.lastPINChangeDate = lastPINChangeDate;
    return this;
  }

  /**
   * Get lastPINChangeDate
   * @return lastPINChangeDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getLastPINChangeDate() {
    return lastPINChangeDate;
  }

  public void setLastPINChangeDate(@javax.annotation.Nullable OffsetDateTime lastPINChangeDate) {
    this.lastPINChangeDate = lastPINChangeDate;
  }


  public ProfileWithoutIdentitiesPIN skippedDate(@javax.annotation.Nullable OffsetDateTime skippedDate) {
    this.skippedDate = skippedDate;
    return this;
  }

  /**
   * Get skippedDate
   * @return skippedDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getSkippedDate() {
    return skippedDate;
  }

  public void setSkippedDate(@javax.annotation.Nullable OffsetDateTime skippedDate) {
    this.skippedDate = skippedDate;
  }


  public ProfileWithoutIdentitiesPIN piNHashingConfig(@javax.annotation.Nullable String piNHashingConfig) {
    this.piNHashingConfig = piNHashingConfig;
    return this;
  }

  /**
   * Get piNHashingConfig
   * @return piNHashingConfig
   */
  @javax.annotation.Nullable
  public String getPiNHashingConfig() {
    return piNHashingConfig;
  }

  public void setPiNHashingConfig(@javax.annotation.Nullable String piNHashingConfig) {
    this.piNHashingConfig = piNHashingConfig;
  }


  public ProfileWithoutIdentitiesPIN PIN(@javax.annotation.Nullable String PIN) {
    this.PIN = PIN;
    return this;
  }

  /**
   * Get PIN
   * @return PIN
   */
  @javax.annotation.Nullable
  public String getPIN() {
    return PIN;
  }

  public void setPIN(@javax.annotation.Nullable String PIN) {
    this.PIN = PIN;
  }


  public ProfileWithoutIdentitiesPIN isPINSet(@javax.annotation.Nullable Boolean isPINSet) {
    this.isPINSet = isPINSet;
    return this;
  }

  /**
   * Get isPINSet
   * @return isPINSet
   */
  @javax.annotation.Nullable
  public Boolean getIsPINSet() {
    return isPINSet;
  }

  public void setIsPINSet(@javax.annotation.Nullable Boolean isPINSet) {
    this.isPINSet = isPINSet;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ProfileWithoutIdentitiesPIN instance itself
   */
  public ProfileWithoutIdentitiesPIN putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProfileWithoutIdentitiesPIN profileWithoutIdentitiesPIN = (ProfileWithoutIdentitiesPIN) o;
    return Objects.equals(this.skipped, profileWithoutIdentitiesPIN.skipped) &&
        Objects.equals(this.lastPINChangeToken, profileWithoutIdentitiesPIN.lastPINChangeToken) &&
        Objects.equals(this.lastPINChangeDate, profileWithoutIdentitiesPIN.lastPINChangeDate) &&
        Objects.equals(this.skippedDate, profileWithoutIdentitiesPIN.skippedDate) &&
        Objects.equals(this.piNHashingConfig, profileWithoutIdentitiesPIN.piNHashingConfig) &&
        Objects.equals(this.PIN, profileWithoutIdentitiesPIN.PIN) &&
        Objects.equals(this.isPINSet, profileWithoutIdentitiesPIN.isPINSet)&&
        Objects.equals(this.additionalProperties, profileWithoutIdentitiesPIN.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(skipped, lastPINChangeToken, lastPINChangeDate, skippedDate, piNHashingConfig, PIN, isPINSet, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProfileWithoutIdentitiesPIN {\n");
    sb.append("    skipped: ").append(toIndentedString(skipped)).append("\n");
    sb.append("    lastPINChangeToken: ").append(toIndentedString(lastPINChangeToken)).append("\n");
    sb.append("    lastPINChangeDate: ").append(toIndentedString(lastPINChangeDate)).append("\n");
    sb.append("    skippedDate: ").append(toIndentedString(skippedDate)).append("\n");
    sb.append("    piNHashingConfig: ").append(toIndentedString(piNHashingConfig)).append("\n");
    sb.append("    PIN: ").append(toIndentedString(PIN)).append("\n");
    sb.append("    isPINSet: ").append(toIndentedString(isPINSet)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Skipped");
    openapiFields.add("LastPINChangeToken");
    openapiFields.add("LastPINChangeDate");
    openapiFields.add("SkippedDate");
    openapiFields.add("PINHashingConfig");
    openapiFields.add("PIN");
    openapiFields.add("IsPINSet");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ProfileWithoutIdentitiesPIN
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ProfileWithoutIdentitiesPIN.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ProfileWithoutIdentitiesPIN is not found in the empty JSON string", ProfileWithoutIdentitiesPIN.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("LastPINChangeToken") != null && !jsonObj.get("LastPINChangeToken").isJsonNull()) && !jsonObj.get("LastPINChangeToken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `LastPINChangeToken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("LastPINChangeToken").toString()));
      }
      if ((jsonObj.get("PINHashingConfig") != null && !jsonObj.get("PINHashingConfig").isJsonNull()) && !jsonObj.get("PINHashingConfig").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `PINHashingConfig` to be a primitive type in the JSON string but got `%s`", jsonObj.get("PINHashingConfig").toString()));
      }
      if ((jsonObj.get("PIN") != null && !jsonObj.get("PIN").isJsonNull()) && !jsonObj.get("PIN").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `PIN` to be a primitive type in the JSON string but got `%s`", jsonObj.get("PIN").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProfileWithoutIdentitiesPIN.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProfileWithoutIdentitiesPIN' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProfileWithoutIdentitiesPIN> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProfileWithoutIdentitiesPIN.class));

       return (TypeAdapter<T>) new TypeAdapter<ProfileWithoutIdentitiesPIN>() {
           @Override
           public void write(JsonWriter out, ProfileWithoutIdentitiesPIN value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ProfileWithoutIdentitiesPIN read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             ProfileWithoutIdentitiesPIN instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ProfileWithoutIdentitiesPIN given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ProfileWithoutIdentitiesPIN
   * @throws IOException if the JSON string is invalid with respect to ProfileWithoutIdentitiesPIN
   */
  public static ProfileWithoutIdentitiesPIN fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProfileWithoutIdentitiesPIN.class);
  }

  /**
   * Convert an instance of ProfileWithoutIdentitiesPIN to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

