// Code generated by the LoginRadius SDK generator; DO NOT EDIT.
//
// The predicates, the error-envelope shapes, the field-alias probing order,
// and the status hints all come from the shared SDK manifest, so every LoginRadius
// SDK classifies and describes the same failure the same way.

package com.loginradius.sdk;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.loginradius.sdk.internal.openapi.ApiException;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;

/**
 * The typed exception thrown by every client method on a non-2xx response or
 * transport failure.
 *
 * <p>Branch on the predicates for the common cases, or inspect
 * {@link #code()}, {@link #description()} and {@link #rawBody()} for
 * diagnostics.
 */
public class LoginRadiusException extends RuntimeException {

  private static final long serialVersionUID = 1L;

  private final int statusCode;
  private final String code;
  private final String description;
  private final String rawBody;

  LoginRadiusException(String message, int statusCode, String code, String description,
      String rawBody, Throwable cause) {
    super(message, cause);
    this.statusCode = statusCode;
    this.code = code == null ? "" : code;
    this.description = description == null ? "" : description;
    this.rawBody = rawBody == null ? "" : rawBody;
  }

  /** HTTP status from the API; 0 when the request never reached the server. */
  public int statusCode() {
    return statusCode;
  }

  /** LoginRadius error code from the envelope; empty for transport errors. */
  public String code() {
    return code;
  }

  /** Long-form description from the envelope, or a status-based hint. */
  public String description() {
    return description;
  }

  /** The response body verbatim. */
  public String rawBody() {
    return rawBody;
  }

  /**
   * Authentication failed — missing or invalid credentials. Distinct from
   * isForbidden: a 403 means the request authenticated but the principal
   * isn't allowed to perform the operation.
   */
  public boolean isAuth() {
    return statusCode == 401;
  }

  /**
   * Authenticated but not allowed. In LoginRadius this commonly indicates
   * IP/domain access restrictions or a feature that isn't enabled on the
   * tenant's plan, rather than a credential problem.
   */
  public boolean isForbidden() {
    return statusCode == 403;
  }

  /**
   * Rate limited by the API.
   */
  public boolean isRateLimit() {
    return statusCode == 429;
  }

  /**
   * A 5xx from the API.
   */
  public boolean isServer() {
    return statusCode >= 500 && statusCode <= 599;
  }

  /**
   * Converts a generated {@link ApiException} into a typed exception.
   *
   * <p>Wire shapes currently modelled:
   *
   * <ul>
   *   <li>{@code ApiError} — The original LoginRadius shape, used by most endpoints.</li>
   *   <li>{@code ErrorResponse} — Variant with an extra HTTP Code field.</li>
   *   <li>{@code ErrorResponseNative} — camelCase fields used by /api/v2/access_token/*.</li>
   *   <li>{@code OAuthErrorResponse} — { error, error_description } from OAuth token endpoints.</li>
   * </ul>
   */
  static LoginRadiusException from(ApiException e) {
    int status = e.getCode();
    String body = e.getResponseBody();

    String code = "";
    String message = "";
    String description = "";

    JsonObject envelope = parse(body);
    if (envelope != null) {
      code = firstNonEmpty(envelope, "ErrorCode", "errorCode", "error_code", "Error", "error");
      message = firstNonEmpty(envelope, "Message", "message");
      description = firstNonEmpty(envelope, "Description", "description", "error_description", "ErrorDescription");
    }

    if (message.isEmpty()) {
      message = !description.isEmpty() ? description : e.getMessage();
    }
    // An empty body is common when an upstream gateway, WAF, or IP
    // restriction blocks the request before the API layer responds, so a
    // status-based hint gives the caller something actionable.
    if (description.isEmpty() && status != 0) {
      description = defaultDescriptionForStatus(status, body);
    }

    String rendered = !code.isEmpty() && !message.isEmpty()
        ? String.format(Locale.ROOT, "loginradius: %d %s (%s)", status, message, code)
        : String.format(Locale.ROOT, "loginradius: %d %s", status, message);

    return new LoginRadiusException(rendered, status, code, description, body, e);
  }

  private static JsonObject parse(String body) {
    if (body == null || body.isEmpty()) {
      return null;
    }
    try {
      JsonElement el = JsonParser.parseString(body);
      return el.isJsonObject() ? el.getAsJsonObject() : null;
    } catch (RuntimeException ex) {
      return null; // non-JSON body
    }
  }

  /**
   * Returns the first non-empty value among the candidate keys, matched
   * case-insensitively so every casing the API uses is handled by one lookup.
   *
   * <p>Only strings and numbers are accepted: LoginRadius sends error codes as
   * numbers and the text fields as strings. A nested object under one of these
   * keys is skipped rather than stringified.
   */
  private static String firstNonEmpty(JsonObject obj, String... candidates) {
    List<String> wanted = Arrays.asList(candidates);
    for (String key : obj.keySet()) {
      for (String candidate : wanted) {
        if (!key.equalsIgnoreCase(candidate)) {
          continue;
        }
        JsonElement v = obj.get(key);
        if (v == null || !v.isJsonPrimitive()) {
          continue;
        }
        String s = v.getAsJsonPrimitive().isNumber()
            ? v.getAsJsonPrimitive().getAsNumber().toString()
            : v.getAsString();
        if (s != null && !s.isEmpty() && !"0".equals(s)) {
          return s;
        }
      }
    }
    return "";
  }

  /** Operator-facing hints for statuses whose bodies commonly arrive empty. */
  private static String defaultDescriptionForStatus(int status, String body) {
    String hint = "";
    switch (status) {
      case 401:
        hint = "authentication failed — verify API key / API secret / access token";
        break;
      case 403:
        hint = "forbidden — typically an IP-access restriction, domain-access restriction, or a plan-level feature gate. Check the LoginRadius dashboard's security settings.";
        break;
      case 404:
        hint = "not found — verify the path and any IDs in the request";
        break;
      case 429:
        hint = "rate limited — back off and retry";
        break;
      case 502:
      case 503:
      case 504:
        hint = "transient upstream failure — retry with backoff";
        break;
      default:
        break;
    }
    String excerpt = bodyExcerpt(body, 240);
    if (excerpt.isEmpty()) {
      return hint;
    }
    return hint.isEmpty() ? excerpt : hint + " — body: " + excerpt;
  }

  /** Single-line snippet of a body, for embedding in a description. */
  private static String bodyExcerpt(String body, int max) {
    if (body == null || body.isEmpty()) {
      return "";
    }
    String collapsed = body.trim().replaceAll("\\s+", " ");
    if (collapsed.isEmpty()) {
      return "";
    }
    return collapsed.length() > max ? collapsed.substring(0, max) + "…" : collapsed;
  }
}
