/* 
 * 
 * Created by LoginRadius Development Team
   Copyright 2025 LoginRadius Inc. All rights reserved.
   
 */

package com.loginradius.sdk.models.requestmodels;
import com.google.gson.annotations.SerializedName;

	// <summary>
	//	Model Class containing Definition of payload for Multipurpose Email Token Generation API
	// </summary>
	public class MultiEmailToken {
	
		
		@SerializedName("clientguid")
        private String clientguid;
		
		@SerializedName("Email")
        private String email;
		
		@SerializedName("Name")
        private String name;
		
		@SerializedName("Type")
        private String type;
		
		@SerializedName("Uid")
        private String uid;
		
		@SerializedName("UserName")
        private String userName;



		// <summary>
		//	Unique ID generated by client
		// </summary>
		public String getClientguid() {
			return clientguid;
		}
		// <summary>
		//	Unique ID generated by client
		// </summary>
		public void setClientguid(String clientguid) {
			this.clientguid = clientguid;
		}
		// <summary>
		//	user's email
		// </summary>
		public String getEmail() {
			return email;
		}
		// <summary>
		//	user's email
		// </summary>
		public void setEmail(String email) {
			this.email = email;
		}
		// <summary>
		//	Name of the customer
		// </summary>
		public String getName() {
			return name;
		}
		// <summary>
		//	Name of the customer
		// </summary>
		public void setName(String name) {
			this.name = name;
		}
		// <summary>
		//	String to identify the type of parameter
		// </summary>
		public String getType() {
			return type;
		}
		// <summary>
		//	String to identify the type of parameter
		// </summary>
		public void setType(String type) {
			this.type = type;
		}
		// <summary>
		//	UID, the unified identifier for each user account
		// </summary>
		public String getUid() {
			return uid;
		}
		// <summary>
		//	UID, the unified identifier for each user account
		// </summary>
		public void setUid(String uid) {
			this.uid = uid;
		}
		// <summary>
		//	Username of the user
		// </summary>
		public String getUserName() {
			return userName;
		}
		// <summary>
		//	Username of the user
		// </summary>
		public void setUserName(String userName) {
			this.userName = userName;
		}
    }