/* 
 * 
 * Created by LoginRadius Development Team
   Copyright 2019 LoginRadius Inc. All rights reserved.
   
 */

package com.loginradius.sdk.models.requestmodels;
import com.google.gson.annotations.SerializedName;

	// <summary>
	//	Model Class containing Definition of payload for OneTouchLogin By EmailModel API
	// </summary>
	public class OneTouchLoginByEmailModel extends ReCaptchaBodyModel {
	
		
		@SerializedName("clientguid")
        private String clientguid;
		
		@SerializedName("Email")
        private String email;
		
		@SerializedName("Name")
        private String name;



		// <summary>
		//	Unique ID generated by client
		// </summary>
		public String getClientguid() {
			return clientguid;
		}
		// <summary>
		//	Unique ID generated by client
		// </summary>
		public void setClientguid(String clientguid) {
			this.clientguid = clientguid;
		}
		// <summary>
		//	user's email
		// </summary>
		public String getEmail() {
			return email;
		}
		// <summary>
		//	user's email
		// </summary>
		public void setEmail(String email) {
			this.email = email;
		}
		// <summary>
		//	Name of the customer
		// </summary>
		public String getName() {
			return name;
		}
		// <summary>
		//	Name of the customer
		// </summary>
		public void setName(String name) {
			this.name = name;
		}
    }